### ISSUE TITLE
Doesn't Work with Spotify Web in Firefox Windows

### ISSUE THREAD

**Issue by cardin** [polywock/globalSpeed#10]
Doesn't work with Spotify Web in Firefox.

Specs:
* Firefox 75.0 64-bit
* Windows 10 PC

**Comment by polywock** [comment]
Thank you for letting me know. It was a bit of a nightmare, but I did manage to fix it. 

### Current Implementation 
To support unconnected media elements (Spotify, NPR, etc). I inject a `<script> my code here </script>` element into the document. I need the code to execute within the page's context to find references to unconnected media elements. 

### Problem 
Spotify sends a Content-Security-Policy (CSP) header which blocks inline code from executing. The problem seems to be browser implementation differences. Even with the CSP, Chrome still lets extensions execute certain types of inline-scripts (like the one I use). However, Firefox only partially executes the code (breaking the functionality). 

### Solution 
Instead of using an inline `<script> my code here </script>`. I changed it into a `<script src="~/file.js">` . Even though Spotify's CSP blocks script src's other than the ones they whitelisted. Chrome/Firefox seem to allow extensions to use any src, as long as it's packaged with the extension and is declared in the extension's manifest file. 

I'm currently working on the v3.0 update, and it might take a few weeks to complete, test, and publish.

**Comment by cardin** [comment]
That's great to know, thank you! 😀

**Comment by polywock** [comment]
I published the extension I made when I was diagnosing this issue. It clears Spotify's CSP headers. You could use that for now. The actual fix might take a few weeks. 

https://github.com/polywock/spotifyCSPClear

https://addons.mozilla.org/en-US/firefox/addon/spotify-csp-clear/

**Comment by polywock** [comment]
I'm glad I built that temporary extension. This update took a while. The Firefox version should work now on Spotify. Let me know if it does. Thanks.  I'll remove the CSP add-on soon.

**Comment by cardin** [comment]
Yeps, it's working fine on Spotify now! Thanks for your hard work!
