### ISSUE TITLE
a bug in Chrome  65.0.3325.146 32bit

### ISSUE THREAD

**Issue by rick999999** [polywock/globalSpeed#103]
hi ,
for the certain reason like running speed and compatibility,
im using a old version of chrome ( 65.0.3325.146 32bit) on my old computer.
the Global speed ext can be installed successfully but the popup.html shows a partial blank rectangle .
the shortcut doesn't work too.
this ext is amazing and thx for your great work.
thx in advance!!!

**Comment by polywock** [comment]
Thank you! But, I don't recommend you use an old version of Chrome because of unpatched security vulnerabilities. I tried figuring out why it's not working, but  Chrome 65 instantly crashes on my computer, so I can't help you there. If all you need is speed control, this old version of Global Speed might work. 

[unpacked.zip](https://github.com/polywock/globalSpeed/files/6874499/unpacked.zip)

1. Download and extract unpacked.zip
2. Open Chrome extensions pag. -> `chrome://extensions`
3. Enable "Developer mode" on the top-right of the page. 
4. Click on Load unpacked on the top-left of the page, and load the extracted folder.
