### ISSUE TITLE
New feature of excluding some urls is helpful.

### ISSUE THREAD

**Issue by billysAnna** [polywock/globalSpeed#104]
New feature of excluding some urls is helpful.

**Comment by polywock** [comment]
Hello. I'm not sure what you mean by exclude, but you can disable shortcut keys depending on the URL. For example, to disable hotkeys if the URL contains "docs.google.com"...

1. Click on the `-- 0 --` button at the bottom-right of the Shortcut Editor section. Here we can configure the URL conditions for the shortcut keys. 

![a](https://user-images.githubusercontent.com/31208859/127279803-0061eb1b-0cd0-49fe-9e22-92eafb9743fd.png)

2. Since we want the hotkeys to remain enabled only if the website isn't "docs.google.com". Add a not equals condition [ != ] if the URL contains the "docs.google.com" keyword.
![b](https://user-images.githubusercontent.com/31208859/127279905-9f9c63b4-5c07-466e-a615-8befd9bd83f0.png)

Also, if you're on a Chromium browser like Chrome or Edge, you can make it so Global Speed only runs on specific websites.

![d](https://user-images.githubusercontent.com/31208859/127282867-a30acb89-053f-493a-9544-57f291436e53.png)

**Comment by billysAnna** [comment]
@polywock Thanks! Using `URL Rules`  is the exact point, not `Shortcut Editor`.

![Snipaste_2021-08-01_16-27-26](https://user-images.githubusercontent.com/12570910/127764662-f46102d8-1b7c-498a-a3a6-16eeea2d1423.png)
