### ISSUE TITLE
PiP steals pause, seak, & fullscreen commands from focused media

### ISSUE THREAD

**Issue by non-bin** [polywock/globalSpeed#109]
**How to reproduce:**
If I have a PiP player open, and media focused in the current tab, the PiP player responds to pause, seak, & fullscreen (does nothing) commands instead of the focused media. Speed controls (I have all tabs pined by default) go to the focused player.

**Intended behaviour**
This is probably intended behaviour, but I like to have music or a stream running while I watch lectures so this is a bit annoying

**Feature request**
I'd like to have an option to configure this. Maybe have an option to automatically select PiP as "preferred video for media hotkeys" so we can disable this functionality

**Comment by non-bin** [comment]
I just had a thought though, it might not be possible to detect when a PiP player is focused? I haven't experimented with them
I'll have a look through the code later today

**Comment by polywock** [comment]
Correct, it's the intended behavior. 

Prioritization goes...
1. User selected video/audio. 
2. PiP video. 
3. Videos visible on the screen.
4. Etc.  

The user can select whatever media they want prioritized using the cursor icon.

![demo1](https://user-images.githubusercontent.com/31208859/128817890-ae59173e-fb91-4f98-9c66-f1fcfa00fd9b.png)

I've implemented your feature request in Global Speed 2.9.3, but as a hidden option since it's kind of niche. The update has been approved for the Chrome and Firefox stores, but will take a week for the Edge Addon store. 

Once updated to >2.9.3. Click on the Help text like 10 times until the hidden command prompt shows up. Enter "toggle pip priority" to disable pip prioritization.

![help](https://user-images.githubusercontent.com/31208859/128821772-15711955-a5b4-497d-b2bb-1df7a039f1c4.png)

**Comment by non-bin** [comment]
Wow thanks 💖

**Comment by polywock** [comment]
No problem, glad to see Global Speed useful. Let me know if you experience other issues or have other suggestions.

**Comment by non-bin** [comment]
Could you make it fall back to the piped video if there is no media selected though? I thing #113 should do it but I can't test it right now

**Comment by polywock** [comment]
Looks good to me. Merged.
