### ISSUE TITLE
[Feature Request] Add import/export options button

### ISSUE THREAD

**Issue by Antyos** [polywock/globalSpeed#11]
I think adding a simple "import/export options as text" button would be a good feature to have. As the name describes, such a button would allow a user to copy the current extension options. The options could either be backed up in a file, or pasted into another browser using this extension. This would be especially convenient to chromium-based Edge users, as extension syncing is still unimplemented.

Without knowing how the settings are currently stored, (I would guess JSON), you may be able to just show a textbox connected to the file.

This isn't a huge deal, so no worries on when you can get to it. If I have some free time, I may attempt a pull request.

**Comment by polywock** [comment]
Thanks for the suggestion. Seems useful, even for Chrome/Firefox because I don't utilize the synced version of the [Storage](https://developer.chrome.com/extensions/storage) API. I'll try to have it implemented in the next version.

**Comment by polywock** [comment]
Hello, an update. I decided against this feature. I still think it's useful, but it will cost me maintenance problems. For example, if the user exports their settings, they would reasonably expect it to be importable a year or more down the line. But, if the settings schema/structure changes, I will be required to support migrating from old versions to new. Normally, this wouldn't be too big of an issue, but because I use Typescript and come to rely on type safety. I would be required to maintain type definitions for old versions. And I don't want to do that. I could go without type safety, but that's scary 😨 .

**Comment by polywock** [comment]
An update. I finally got around to implementing this in the latest update (after getting more demand). Thanks for the initial suggestion.
