### ISSUE TITLE
unable to sign in github's oauth

### ISSUE THREAD

**Issue by thisguychris** [polywock/globalSpeed#12]
Hi @polywock 👋

So I've been using this extension for quite a while since I moved to the chromium-based edge. I find it pleasant to work with. I love the big icon indicators when I forward and rewind and also when I change the video speed. So thank you for making this.

Recently I discovered a weird bug, I'm trying to sign in to a [repl ](https://svelte.dev/repl) which uses GitHub as SSO, but this extension seems to prevent it to let me sign in. If I disable the extension it works fine.

**Comment by polywock** [comment]
Thanks. I tracked the bug down and figured out a fix. Unfortunately, I'm currently working on the version 3 update and it might take a few weeks to push the fix.  As a temporary workaround.  For now, when signing in via oauth, you can suspend the extension via the power icon. 

## Problem 
To support unconnected media elements (think hidden) like those on Spotify, NPR, Amazon Music, etc. I couldn't just sift through the DOM (the standard way). I had to inject a script into the page's scope to hijack certain functions that allow me to capture references to said unconnected media elements. So the extension has two parts in a way, one part handles connected media elements, the other handles unconnected ones. 

To talk between each other, I use `window.postMessage()`. But, with my current implementation, the website's script can also listen to these messages. This isn't usually a problem because websites who use it typically listen to specific messages. But, `svelte.dev` seems to close the window if it receives any kind of message. I indeed confirmed that to be the case by looking through the script files. 

``` 
// code snippet from "svelte.dev"
window.addEventListener("message", function t(s) {
    e.close() 
    // ... 
}
```

## Solution 
Add my listener first (already the case) and stop propagation to avoid the websites' scripts from reading/reacting to my business.

**Comment by thisguychris** [comment]
Thanks for the quick fix! Looking forward to the push. This extension rocks! It's better than what I previously was using. 👌

### Unrelated Issue
Just a side comment the invert function was really annoying 🤣 I couldn't find what happened. Why all my sites seem to be inverted. I didn't realize I accidentally pressed the hotkey. Also for some reason, I feel that the page is sluggish when I have the invert on. Not sure if it's a memory leak.

**Comment by polywock** [comment]
Yeah, that shortcut was terrible UX design. I've received many reports about that. The latest release had the shortcut disabled by default. You must have installed it pre-fix. As for performance for the invert, I haven't personally noticed any issues myself. But, I'll make sure to look through that code again and optimize what I can. Thanks again for the feedback.
