### ISSUE TITLE
Capture option

### ISSUE THREAD

**Issue by Armitxx** [polywock/globalSpeed#132]
Keys cannot be changed in Capture option

**Comment by polywock** [comment]
Hey, Armitxx. The Capture hotkey is configurable, but only through the browser's native shortcut editor. This is because the API used to manipulate the tab's audio requires the user to first invoke the extension, and only shortcuts configured through the browser's native shortcut editor can invoke an extension.

### To setup...

1. Create a Capture hotkey. 
![ba](https://user-images.githubusercontent.com/31208859/133805634-f75e804c-2e31-4094-b289-35ae34bec318.png)

2. Bind it to "Command A". Click on the link icon to go to the browser's shortcut editor. 

Chrome: chrome://extensions/shortcuts
Edge: edge://extensions/shortcuts

![bb](https://user-images.githubusercontent.com/31208859/133805662-56f42338-8cbb-4d89-af7a-426874a0e126.png)

3. Click the pencil icon and configure your preferred key. 

![bc](https://user-images.githubusercontent.com/31208859/133806015-1cd3454e-6e70-4c24-b47e-fa0c3b6acc04.png)
