### ISSUE TITLE
Shortcus don't work when PiP is focused

### ISSUE THREAD

**Issue by non-bin** [polywock/globalSpeed#134]
If I select the PiP window, keyboard shortcuts don't work, but if I have the PiP window open but focus a tab with no media, shortcuts work as intended

Not sure if extensions can run in PiP context

**Comment by polywock** [comment]
You may need to turn the keys global. Example video. 

https://www.youtube.com/watch?v=EZA-TnVAyDo

**Comment by non-bin** [comment]
Yeah that worked, but there's a limit to how many I can have, they have to be key combinations, and they have to be fully global, not just within chrome and I've run out of key convenient combinations to spare (I love hotkeys)
Can extensions do anything with PiP aside from activate/deactivate?

**Comment by polywock** [comment]
Only the standard media operations like seek, adjust volume, AB loop, marking, etc. It would be nice to be able to control position, size of the PiP window, but the PiP API is very limited right now. 

I don't recommend setting too many. Global hotkeys are very aggressive by nature. As long as you set them up and have Chrome open, no other program will be able to listen to that key combination. They require key combinations because If you're able to set one for "S", you won't be able to type anywhere.  The only way to stop them is to kill Chrome, disable Global Speed, or clear the shortcut key (through Chrome's shortcut editor). 

Global Speed will warn you if you delete a Global hotkey like "Pause = Command X" from Global Speed's option page, but still have the "Command X" binded to a key combination in Chrome's shortcut editor. 

![img5](https://user-images.githubusercontent.com/31208859/134531626-09b9bf8f-83e3-4333-b1aa-e729fdde4532.png)
