### ISSUE TITLE
Idea：Press set & Release back

### ISSUE THREAD

**Issue by WebroLam** [polywock/globalSpeed#145]
Press and hold a hotkey to take effect x speed, release to set back the last speed. This may be a nice feature ？

**Comment by polywock** [comment]
Hello. i've thought about implementing this, but decided against it because I'm lazy and a similar thing can already be done. If you add a hotkey to set speed to "10x". Once triggered, it will go to 10x and if you trigger it again, it will revert back to your last speed. Not as convenient as set/release, but convenient enough I think. 


![img4](https://user-images.githubusercontent.com/31208859/142436644-cca56051-2174-44b4-8e8c-41454259a96a.png)

**Comment by orkhan10** [comment]
I implemented this. Very useful! Thanks for letting us know @polywock

**Comment by WebroLam** [comment]
> 

I'm sorry for your laziness, but thank you for your plug-in. It's really powerful.

**Comment by WebroLam** [comment]
> Hello. i've thought about implementing this, but decided against it because I'm lazy and a similar thing can already be done. If you add a hotkey to set speed to "10x". Once triggered, it will go to 10x and if you trigger it again, it will revert back to your last speed. Not as convenient as set/release, but convenient enough I think.
> 
> ![img4](https://user-images.githubusercontent.com/31208859/142436644-cca56051-2174-44b4-8e8c-41454259a96a.png)

I'm sorry for your laziness, but thank you for your plug-in. It's really powerful.

**Comment by polywock** [comment]
No problem. Glad to see my plug-in useful.
