### ISSUE TITLE
同一个网站能否定义多个规则   每个标签看视频 设置不同的加倍速度

### ISSUE THREAD

**Issue by ylsds** [polywock/globalSpeed#149]
比如 youtubee.com 的视频  是否可以设置多个  加速规则 .  第一个视频 2倍,第二个视频3倍,  下次看视频的时候 不会覆盖. 

也就是加速规则的优先级

**Comment by polywock** [comment]
Hello. If I'm understanding correctly (language barrier), you created a rule that changes speed to 2.0x if the URL matches youtube. But, you want it so that if you change the speed to 3.0x, it won't revert back to 2.0x once you load a different video? If I understood correctly, try enabling the "ILO" mode so the URL rule only runs on the initial page load. That way if you load a different video, it won't activate the URL rule again. 

![demo4](https://user-images.githubusercontent.com/31208859/143731028-86a2fe29-689c-49b5-8473-c93d15f124a4.png)

URL rules are a bit complicated and I might remove them in the next major update. Better to just use the shortcut keys to change speed (A-S-D keys by default). As long as the tab is pinned  📌, each tab can have separate speeds.  If you prefer all tabs having a separate context by default. You can enable "pin by default"  📌  in the options page (默认固定). 

![demo2](https://user-images.githubusercontent.com/31208859/143529001-ed548f4f-4863-4e36-88df-14be14452e55.png)

**Comment by ylsds** [comment]
.thiank you , you teach me , I have&nbsp; understood&nbsp; .





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "polywock/globalSpeed"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月28日(星期天) 中午1:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [polywock/globalSpeed] 同一个网站能否定义多个规则   每个标签看视频 设置不同的加倍速度 (Issue #149)





 
Hello. If I'm understanding correctly (language barrier), you created a rule that changes speed to 2.0x if the URL matches youtube. But, you want it so that if you change the speed to 3.0x, it won't revert back to 2.0x once you load a different video? If I understood correctly, try enabling the "ILO" mode so the URL rule only runs on the initial page load. That way if you load a different video, it won't activate the URL rule again.
 

 
URL rules are a bit complicated and I might remove them in the next major update. Better to just use the shortcut keys to change speed (A-S-D keys by default). As long as the tab is pinned  📌, each tab can have separate speeds.  If you prefer all tabs having a separate context by default. You can enable "pin by default"  📌  in the options page (默认固定).
 

 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
