### ISSUE TITLE
Change default hotkeys to standard

### ISSUE THREAD

**Issue by NayamAmarshe** [polywock/globalSpeed#16]
Most video control extensions have these as standard hotkeys:
Increase speed - D
Decrease Speed - S
Adjust/Switch Speed (between normal and last used speed) - R
Seek Forward - X
Seek Backward - Z

The last 2 were already set. Would be great if you could set these new. Of course not necessary but it would be great if implemented since all other video control extensions I have used before have the same key bindings.

**Comment by polywock** [comment]
I'm afraid you have [Stockholm Syndrome](https://en.wikipedia.org/wiki/Stockholm_syndrome). The ASD keys are far superior. Joking aside, I do prefer the ASD keys because they're sequential and more intuitive (without prior using a different extension). All keys are customizable in the settings, so it doesn't really matter that much.  

In the next version, the speed set shortcut key will toggle between set speed and the last used speed (see #13).
