### ISSUE TITLE
A few ideas

### ISSUE THREAD

**Issue by daveox** [polywock/globalSpeed#161]
First of all, what a lovely extension you got. 

I've just created this account just to give some ideas about it.

1- Negative delay values.

2- Individual panning for the left and right channels.

3- The normalize feature like in the MPC-HC, MPC-BE, Pot Player, etc.

I don't know much you know about effects but, it essencially turns down loud sounds and turns up low sounds, making them more even.

4- I'm not sure if that's a bug but, on youtube, instagram, etc, the backdrop filters settings are changing the images/videos thumbnails, like in the global speed video demo. I'm still using the Dark Reader extension for this.

5- The big one. Its really begging for a presets feature and shortcuts for them.

Since there are too many things that can be done with it and a lot of them are constantly used in the same way,  I guess that would be the most logical and fastest way to get the most out of the extension.

For example, for mirror videos, I would simply save a preset with scaleX in "-1" and a shortcut for it, instead of reset all the parameters previously used (that I probably wouldn't even remember which ones were) and do the same thing every single time for a different use.

Moreover, even if there was a shortcut for every single setting in the extension, which would be a hell of job for you to make it, I guess, and even for the users to deal with it, a lot of times, I'll have to tweak more than one setting, e.g., if I want to zoom a 21:9 video to watch it in a 16:9 screen without black bars, etc.

Happy New Year ;)

**Comment by polywock** [comment]
Thanks! Hope you had a great new year as well. 

1. There's a [great extension](https://chrome.google.com/webstore/detail/youtube-audiovideo-sync/mknmhikmjljhpccebpnplhicmcfjkgbk?hl=en) that can do this for Youtube. But, that extension's approach cannot be extended to other websites. I've looked into a general solution that works on all sites, but I don't think it's possible. 
2. I'll look into implementing this in the next update. But, it may take a while. I'm waiting for Manifest V3 to stabilize before I make any changes. 
3. It seems the best normalization can only be done if you have access to the entire audio file at once. For realtime audio, I tried using the Web Audio API's DynamicsCompressorNode, but the results weren't good. 
4. Not a bug. The backdrop filter applies to the entire page. I called it backdrop because I use the "backdrop-filter" CSS property. I should probably rename it to "page" or something. 
5. I thought about implementing presets, but most of it can already be done using the Shortcut Editor in the options page. You can bind multiple shortcut commands to the same shortcut key (they run in order from top down). Image example attached below (might need be visible if you're viewing through email). 

![filter](https://user-images.githubusercontent.com/31208859/147953923-04f2c725-c81e-45d3-becc-9df76736d9dc.png)

**Comment by daveox** [comment]
1. I tried YouTube Audio/Video Sync but, the audio was glitching, wich, actually, was what made me look for an alternative, till I found your extension for that purpose, which just works.

3. For free, I use the 0 latency Reaper plugin JS: VOLA Voice Optimized Leveling Amplifier (thats just a .txt file with some open code). I'm not sure if it is possible to use it somehow.

There's also a free vst version https://plugins4free.com/plugin/2594/

4. I'm not sure if this can be to implemented but, it would be awesome if it I could use your extension like Dark Reader works. Personally, I couldn't think of a 'normal' use where I would want the images/ videos/ thumbnails to be affect by the filters settings.

5. I won't pretend I get the logic behind every step of your printscreen (thanks for that) but,  I just did this for the mirror idea.

![image](https://user-images.githubusercontent.com/96954096/147972773-ecfc94ac-6650-4613-b4eb-bcd88501d68f.png)

The way it is right now, its a 2 steps process (on/off) for a single simple idea.

Combining 2, 3, things for every new macro/idea would be overwhelming.

I was thinking of the presets more like a toggle shortcut for 'save the current state of the extension'.

That could potencially turn a steps 10 idea, for example, into 1 single step/shortcut.

6. Really not that relevant but, personally, on/off makes more sense to me than capture/release. It took me a while to understand it and... the extension name... of, man, as must know, is does 'a little more' than just the 'speed thing'. More people need to know about this. ;]

**Comment by polywock** [comment]
Feel feel to suggest ideas any time. But, it might take a while to implement them. I'm currently waiting for Manifest V3 to stabilize before implementing new features because Manifest V3 has a lot of changes and I'll have to rewrite most of the extension and I don't want to implement stuff just to have to rewrite it later. All Chrome extensions most migrate to Manifest V3 by January 2022. 

1. Good idea, will try to implement that in the next update. But, audio delay already is possible in shortcuts. 
2. I actually did try to implement that already, but it requires using an SVG filter, which I found has some limitations compared to the normal filters so I ended up dropping it. I'll look into SVG filters again to see if I can figure out any solutions to my previous problems.
3. Interesting issue, I'm not sure why. Do other shortcuts like speed adjustment work? The only thing I can think of is that you're on a New Tab page, which doesn't have Global Speed running. 
4. Yeah, that is annoying. But, I'll probably not end up implementing this as I don't want to overwhelm users with too many options. Usually I just reset the speed back to 1.0. You could also create a shortcut to set speed to 0.1 and use that when you go past 0.7. 
5. I'll try to give hotkeys that use list of values an optional hotkey to reset to the first value. You can set this hotkey to the same one as Reset FX if you want them to work in tandem. I'll also try to implement an optional hotkey to walk backwards the list of values. 

Thanks! Always glad to see the extension useful.
