### ISSUE TITLE
Sugestão

### ISSUE THREAD

**Issue by MauricioCastioni** [polywock/globalSpeed#176]
Olá poderia por o tempo que vai demorar o vídeo com a velocidade escolhida e mostrar fixo em algum local da tela.

**Comment by polywock** [comment]
Hello. I've considered this before, but decided against it. Putting it on some random corner is possible, but it doesn't look nice. It would be ideal to show the new duration where it displays the real duration, but that would be impossible because each website's HTML structure and code is different. But, I do think it's a good idea to let the user know of the real speed. In the next update, I think i'll show the new duration in Global Speed's menu. 
![test2](https://user-images.githubusercontent.com/31208859/154722525-972ecd2a-80ed-4949-8aa0-5fe3e4da4513.png)

**Comment by MauricioCastioni** [comment]
poderia ter como fixar o mostrador da velocidade no vídeo e por junto o tempo que vai levar. Só outra forma.

**Comment by polywock** [comment]
Hello. Apologies for the late reply. Going through the old issues one by one. As of today, this feature is still now supported. But, there's a new "show media info" shortcut that temporarily prints out the adjust time. Not the feature you requested, but maybe still helpful.
