### ISSUE TITLE
How does it work? Documentation?

### ISSUE THREAD

**Issue by nasdas-dev** [polywock/globalSpeed#181]
Hi @polywock 

Awesome work here. Looking forward to use this plugin in a personal project of mine. Is there any documentation of the  architecture / functionality of your work? Or can you give me some hints to find the most important components / modules in this project?

Many thanks & again, great work!

**Comment by polywock** [comment]
Thank you! Apologies for the late reply. Unfortunately, there is currently no documentation. I also comment less than I should. The project uses Webpack, React, and Typescript.  Since you didn't elaborate any details on your personal project, I can't really say what would be important or not. Depending on your use case, 90% of the project can be thrown away. Here's a basic outline. Feel free to ask any specific questions. 

src/contentScript # everything related to the content script (the script that runs on the webpages itself). 
src/background # everything related to the background page (the script running in the background). 
src/options # everything related to options page. 
src/popup # everything related to the popup page (when you click the extension icon). 
src/utils # helper functions or functions not specific to just a single section. 
src/comps # react components used in options page, popup page.

**Comment by yo1995** [comment]
I'm also curious about the intrinsics of this plugin. From a quick glance, the key is to adjust the playbackRate / requestRate for the requests on various video hosting websites. The key logics are in [`contentScript/main`](https://github.com/polywock/globalSpeed/tree/master/src/contentScript/main).
Still, it seems to be a great chunk of work to ensure it works for so many different video players. So kudos to the author! 🌹

**Comment by polywock** [comment]
Thanks! 

> I'm also curious about the intrinsics of this plugin. 

Global Speed's core functionality can be simplified to the following code. Every one second, find all video and apply the desired speed. 

```ts
setInterval(async () => {
  for (let elem of document.getElementsByTagName("video")) {
    elem.playbackRate = speed
  }
}, 1000)
```

> The key logics are in `contentScript/main`

Funny enough the folder name is actually misleading. The `isolated/` folder on the same directory is more important.  It's named that way because extension content scripts can run in two worlds (ISOLATED or MAIN). Most extensions just need the ISOLATED world but Global Speed also needs the main world for a few features (ghost mode, Netflix, Youtube, etc).
