### ISSUE TITLE
Playback freeze during speed change - Windows 11

### ISSUE THREAD

**Issue by michalpl7** [polywock/globalSpeed#184]
Hello, I'm having weird issue with playback freeze for around 1 s when changing playback speed on laptop.
On my second PC this does not happen playback speed change is invisible.

Checked in Netflix and Amazon Prime same problem.

Browser version on both the same: Edge 99.0.1150.46 ( 64 bit )

Laptop is: Windows 11 ( 21H2 )
PC is: Windows 7 SP1

Any idea what might be wrong on laptop?

Greetings.

**Comment by polywock** [comment]
Hello. Greetings to you as well. First time I'm hearing about this type of issue. A few steps to help diagnose the issue. 

1. Does reinstalling Global Speed fix the issue? If it did, the issue was probably Global Speed related.
2. Does this bookmarklet also freeze your playback? Make sure to uninstall Global Speed while trying this out. To create a bookmarklet, edit any existing bookmark (Edge Favorite) and set the url to the following code. Once clicked, it will toggle between 0.5x speed and 3x speed. Do you still experience that freezing issue? 

```javascript
javascript:(()=>{
    var video = document.querySelector("video");
    video.playbackRate =  video.playbackRate === 0.5 ? 3 : 0.5; 
})()
```

**Comment by michalpl7** [comment]
Hello, 

I also checked another laptop with Windows 10 and there is the same issue with freeze.

Interesting thing I tested HBO Max and this is not affected ( only Netflix and Amazon Prime ), playback is smooth during change speed. Maybe this is somehow related to DRM - testing on Windows 7 is not affected maybe because that Widevine DRM? This is quite annoying :/

This is not related to Your extension because installing different one gives the same problem.

1. Reinstalling does not help.
2. Not sure how to do this, created Favourite Bookmark of Prime, and put there that code in URL. But nothing happen when I click it.

**Comment by michalpl7** [comment]
This is it! That PlayReady DRM is responsible for this issue! Now I can change speed smoothly. :) Huge thanks!

What is that PlayReady DRM? Do I need it for something? This might lower quality of HBO/NF/Prime?

**Comment by polywock** [comment]
I think without PlayReady DRM, Netflix will only pay videos up to 720p resolution. However, there are extensions that can force up to 1080p playback, but if you have 4K Netflix Plan, you won't be able to play it.

**Comment by michalpl7** [comment]
Yes NF plays only HD 720p :/. I have 4K Plan.
