### ISSUE TITLE
[bug]使用该软件全屏后，该软件其它操作的tips将无法显示

### ISSUE THREAD

**Issue by godefy** [polywock/globalSpeed#187]
使用该软件全屏后，该软件其它操作的tips将无法显示。比如全屏后，再按加速减速的快捷键，可以正常生效，但tips显示不出来。
如果是使用视频网站默认的全屏方式，则没有影响。

-----------------

After using the software in full screen, the tips for other operations of the software will not be displayed. For example, after the full screen, pressing the shortcut keys of acceleration and deceleration can take effect normally, but the tips cannot be displayed.
If you use the default full screen mode of the video website, it will have no effect.

**Comment by polywock** [comment]
Hi. The fullscreen hotkey has two modes. In the default mode, it's not possible to show the indicator tips. You can change
the mode by clicking this button.

![img1](https://user-images.githubusercontent.com/31208859/160294401-9ce2735f-393b-432f-aacc-2983c92ee2bf.png)

Native Mode (简单模式): enters fullscreen mode directly on the video element and activates the HTML5 native controls. While a video element is directly fullscreen, it's not possible to show anything extra, including the popup tips. 

Standard Mode: this mode is like clicking on the player's fullscreen button. It tries to enter fullscreen mode on the container element to mimic the website's standard fullscreen behavior. This method requires learning. If you visit a new website, you must manually click on the fullscreen button at least once. Otherwise, Global Speed won't know which element is the container element.

**Comment by godefy** [comment]
谢谢，非常有效。我设置成以下模式以后，tips可以正常显示了：
![image](https://user-images.githubusercontent.com/19462833/160739856-0097f2ed-ab66-4bc1-832e-d8a29980b430.png)
建议把这部分说明补充到插件的提示里，我之前也是不太理解那个"简单模式"的作用，试了几次也没发现区别。

---------------------------------------------------------------------------------------

Thanks, very effective. After I set it to the following mode, the tips can be displayed normally: 
![image](https://user-images.githubusercontent.com/19462833/160739856-0097f2ed-ab66-4bc1-832e-d8a29980b430.png)
It is recommended to add this part of the description to the plug-in prompt. I didn't quite understand the function of the "simple mode" before, and I didn't find any difference after trying it several times.

**Comment by polywock** [comment]
Hello. In the version 3 update, it's now possible to see the indicators in both modes.
