### ISSUE TITLE
[Recommendation] Hope to support configuration synchronization

### ISSUE THREAD

**Issue by godefy** [polywock/globalSpeed#188]
It seems that choosing Google Chrome provides a way to configure synchronization, and many plugins have already configured cloud synchronization. But this plugin is not yet supported, I hope to support it.

**Comment by QuarticCat** [comment]
Any update? It seems like this could help: https://developer.chrome.com/docs/extensions/reference/api/storage#storage_areas

**Comment by polywock** [comment]
Hi. Due to a MV3 migration issues, progress on Global Speed pretty much stalled for 2 years. Although, I would love to implement sync, it's not looking great. 

I'm about done with the upgrade, but I decided against sync for a few reasons. The new structure of Global Speed requires fast storage read/writes. I've ran benchmarks and the sync storage space is 5x slower which makes it less than ideal. Although, I did try working around it, however that introduced too much complexity. 

I'll shelve the feature for now, but hopefully if new proposals like `onChanged filters` get implemented by the browsers, I could look into implementing it again.

**Comment by homura144** [comment]
> Hi. Due to a MV3 migration issues, progress on Global Speed pretty much stalled for 2 years. Although, I would love to implement sync, it's not looking great.
> 
> I'm about done with the upgrade, but I decided against sync for a few reasons. The new structure of Global Speed requires fast storage read/writes. I've ran benchmarks and the sync storage space is 5x slower which makes it less than ideal. Although, I did try working around it, however that introduced too much complexity.
> 
> I'll shelve the feature for now, but hopefully if new proposals like `onChanged filters` get implemented by the browsers, I could look into implementing it again.

Hi, I’d like to revisit this feature request now that some time has passed.

I understand the concern from the previous discussion: `storage.sync` is significantly slower than `storage.local`, and using it directly for Global Speed’s runtime state would add latency and complexity.

Would it be feasible to separate the two roles instead?

* Keep `storage.local` as the source of truth for all runtime reads/writes.
* Treat `storage.sync` only as a low-frequency synchronization layer for user configuration.
* When settings are changed, debounce/batch the update and mirror only the persistent configuration to `storage.sync`.
* On extension startup / browser profile change, merge or restore the synced configuration into `storage.local`.
* Exclude transient/runtime state from sync entirely.

This should avoid putting `storage.sync` on the hot path, while still providing seamless cross-device settings sync for users with multiple browsers/devices. The existing import/export feature is useful, but native browser sync would make this much more convenient.

If the configuration can exceed per-item sync quotas, it could potentially be split into a few logical keys (shortcuts, site rules, audio/video settings, etc.) rather than moving the whole runtime storage model to `storage.sync`.

Would this architecture make sync practical with the current MV3 version of Global Speed?
