### ISSUE TITLE
Do not force the speed always to be same as extension setting

### ISSUE THREAD

**Issue by Laster2800** [polywock/globalSpeed#19]
For example, the website has its own speed control (0.2x-2.0x), I just want to use globalSpeed when I need speed > 2.0x.
But now, when I set the speed by website setting, the speed will change back to globalSpeed setting. Offer a option to stop fixing speed.

And I think there is a bug here, because SOMETIMES the speed will not change back. I don't know how to reproduce it.

**Comment by polywock** [comment]
As for the first suggestion. Global Speed is designed to be a top-down controller, meaning it's speed value overrides everything below. Having multiple "sources of truth" can become difficult to implement. Why not just suspend the extension using the ⏻ power icon? You could also add a `set state` shortcut key to do that more conveniently. 

As for the bug. Does refreshing the page help? I'm not sure what the cause is. I've refactored the code recently for the version 3 update, so I might have already fixed it (or not).

**Comment by Laster2800** [comment]
OK, I accept the design, just use shortcut to switch the state.
As for the bug, I can't remember more details.

**Comment by polywock** [comment]
Thanks for quick reply. There might be different extensions that
