### ISSUE TITLE
建议增加只有在媒体资源的网站才开启热键的功能

### ISSUE THREAD

**Issue by HepingGe2333** [polywock/globalSpeed#226]
在诸多无媒体功能的网站（如github）上，关闭热键，否则会与很多网站的热键造成冲突（如github的搜索快捷键s）。

**Comment by ChineseZhuYvhang** [comment]
在诸多无媒体功能的网站（如github）上，关闭热键，否则会与很多网站的热键造成冲突（如github的搜索快捷键s）。

**Comment by polywock** [comment]
Hello. Due to the the underlying structure of the code, it will be a great effort to that. As a workaround, you could add Github to the shortcut URL conditions. 

![im1](https://user-images.githubusercontent.com/31208859/177248026-f5b2d464-f3f0-48ad-968e-6867610d5486.png)

![im2](https://user-images.githubusercontent.com/31208859/177248030-5e495d05-aa2b-4a02-8092-93860b13b5db.png)
