### ISSUE TITLE
YouTube sounds ragged when using the battery

### ISSUE THREAD

**Issue by Cabus1982** [polywock/globalSpeed#228]
Hi, I have a problem using the EQ (no speed changes) in battery mode, the audio sounds annoyingly choppy, when I connect to the AC the problem disappears. I have the Windows and Edge Browser profiles in high performance in both, I have no extensions or active optimization functions, all updated and the problem persists. 🤔

Ultrabook Dell 7480 (i7 7600U - 16 GB)

**Comment by polywock** [comment]
Hello. Seems like a battery saving optimization, even if it should be disabled. Not sure if the issue is fixable. Maybe try this version. I added a very low latencyHint instead of leaving it unspecified. 

https://developer.mozilla.org/en-US/docs/Web/API/AudioContext/AudioContext#latencyhint

1. Open `edge://extensions`. 
2. Disable the original Global Speed. 
3. Enable developers mode. 
4. Download packed.zip and unzip the folder. 
5. Click "Load unpacked" and load the folder. (ignore the Manifest v2 depreciated warning, haven't updated yet).  

[packed.zip](https://github.com/polywock/globalSpeed/files/9074576/packed.zip)

**Comment by Cabus1982** [comment]
Didn’t get any better

**Comment by polywock** [comment]
Global Speed uses the Tab Capture API to get tab's audio, and the Web Audio API (particularly the [BiquadFilterNode](https://developer.mozilla.org/en-US/docs/Web/API/BiquadFilterNode) for the EQ feature). I suspect it's a chromium issue with one of these. You can run this bookmarklet while a Youtube video is playing to narrow it down. This circumvents Tab Capture API so if this works (not choppy), the issue is with the Web Audio API instead. 

1. Edit any bookmark and set the URL to the following code. As for name, you can choose anything. 
2. Click on the bookmark while a Youtube video is playing. 
3. Let me know if it sounds choppy or not (when you're using battery). 

```javascript
javascript:(() => {
    const video = document.querySelector("video")
    const ctx = new AudioContext()
    const mediaSrc = ctx.createMediaElementSource(video) 
    const filter = ctx.createBiquadFilter()
    filter.freq = 1000
    filter.gain = 0 
    filter.q = 1.4 
    mediaSrc.connect(filter) 
    filter.connect(ctx.destination) 
})()
```

**Comment by polywock** [comment]
I just noticed an issue with the bookmarklet code. Forgot the semicolons so it wouldn't have run. My bad. 

1. Edit any bookmark and set the URL to the following code. As for name, you can choose anything. 
2. Click on the bookmark while a Youtube video is playing. 
3. Let me know if it sounds choppy or not (when you're using battery). 

```javascript
javascript:(() => {
    const video = document.querySelector("video");
    const ctx = new AudioContext();
    const mediaSrc = ctx.createMediaElementSource(video);
    const filter = ctx.createBiquadFilter();
    filter.freq = 1000;
    filter.gain = 0;
    filter.q = 1.4;
    mediaSrc.connect(filter);
    filter.connect(ctx.destination);
})()
```

**Comment by Cabus1982** [comment]
It wasn't really necessary, now it's working well. Maybe an extension or browser update?

Extension: 2.9.95
Browser: 103.0.1264.49 (Official build) (64-bit)

**Comment by Cabus1982** [comment]
Unfortunately, when I clic on the bookmark the sound of the video become weak and gray and the choppy sound still there. 😢

**Comment by polywock** [comment]
The sound becoming weak is normal because of the Biquad filter. But, since it's still choppy, that means the issue is with the Web Audio API. Edge also uses Chromium, so it's very likely a Chromium bug. To confirm, try the bookmarklet on Chrome as well. 

If you want, you could report this issue to the Chromium team. Only way I see this issue being resolved. 

https://bugs.chromium.org/p/chromium/issues/list
