### ISSUE TITLE
请问如何让每个新打开的标签默认都是1倍速，调整一个标签倍速不影响其它标签

### ISSUE THREAD

**Issue by willaytoun** [polywock/globalSpeed#231]
比如我YouTube其中一个视频2倍速，但是我不想再点其它视频也是2倍速，这个怎么设置啊？

**Comment by amanteae** [comment]
設速的地方畫面左上角有個大頭針，把那個tab 的速度釘起來，專門給他2倍速。其他沒釘的都是global 設定

**Comment by amanteae** [comment]
![image](https://user-images.githubusercontent.com/21978129/179144291-4969ed90-da07-4f81-8a4c-33f25a919bc4.png)

**Comment by willaytoun** [comment]
好的，也就是说一个视频调整到2倍速之后不想让其它标签页受影响的话要先点大头针。这样设计的话会不会比较繁琐呀，因为我这边每个视频倍速基本都不太一样，默认1倍或几倍然后进视频再调整不是更好吗？

**Comment by polywock** [comment]
Hello. If you want the default speed for new tabs to be 1x.  

1. Make sure the tab is not pinned and set speed to 1x. 

![imgg2](https://user-images.githubusercontent.com/31208859/178054171-da1fc5ce-a4e2-464b-bb66-daa7c9bcba1e.png)

2. Enable  "pin by default" (默认固定) in the options page. All new tabs will inherit the global speed. (which will be 1.0x) 

![imgg1](https://user-images.githubusercontent.com/31208859/178053659-325115c6-e1a5-4502-897c-465df024a8c9.png)

Make sure inherit global (继承全局) is enabled, otherwise new tabs will inherit the previous tab's speed.

**Comment by willaytoun** [comment]
已设置成功，非常感谢😀
不过这样最开始的那个标签页必须是1倍速如果这个标签页更改倍速就影响后面所有标签页了对吧？

**Comment by xianghongai** [comment]
![Vspeed Controller](https://user-images.githubusercontent.com/2075006/188070452-c9b660fa-edc5-46e0-a56e-4f7aee3f292f.png)

**Comment by polywock** [comment]
Update: The pin by default mode now supports "new context" where all new tabs will start at 1x speed.

**Comment by willaytoun** [comment]
非常感谢，这个功能对我来说非常实用😀
