### ISSUE TITLE
auto fullscreen on youtube bilibili etc.

### ISSUE THREAD

**Issue by k22725** [polywock/globalSpeed#237]
Global Speed 
![image](https://user-images.githubusercontent.com/109954254/180746036-f2fcc5d9-99a0-4616-9310-65f7545a88d6.png)
Can use javascript auto send "F"(on youtube bilibili press “F” can fullscreen)that will save many many times.
my english and programming are very poor,  跪求大神赐予解决方案（Pray for God's solution）

**Comment by polywock** [comment]
Hello. Unfortunately, not possible. If you try simulating "F" key press with URL rule it gives off this error message. 

`Failed to execute 'requestFullscreen' on 'Element': API can only be initiated by a user gesture.` 

Fullscreen can only be initiated by the user for safety reasons. Otherwise, a malicious script could discretely initiate fullscreen and pretend to be a trusted website (bank, etc) and hijack user information.  

You can learn more about this type of phishing attack from this article. 

https://feross.org/html5-fullscreen-api-attack/
