### ISSUE TITLE
Which open source/free software license does this web extension follow?

### ISSUE THREAD

**Issue by ZhouJiatai** [polywock/globalSpeed#247]
This is such a nice web extension that I use it almost every day. But I can't find any open source/free software licenses under the source code folder now. The file `package.json` in the source code of "tag v2.5.1" shows that it followed the ISC license at that time. 
Line 10 in `package.json`:

    ...
    "license": "ISC",
    ...

However, today I can't find this line any more. So which open source/free software license does this web extension follow now? Or it doesn't follow open source/free software licenses at present?
(I am not a native English speaker. If there are any mistakes of grammar, please understand me.)

**Comment by polywock** [comment]
Hello. Apologies for the confusion. There never was a license. Global Speed is source code available, but all rights reserved so far.  I will try researching about licenses soon.  

If you initialize an NPM package using the `npm init -y` command, it will put `"license": "ISC"` by default and wasn't intended. I removed that line after finding out. If I read correctly, unless you see a LICENSE file, always assume no license. The license line on `package.json` is only intended for NPM packages published on `npmjs.com`.

**Comment by polywock** [comment]
@andreyplus Unless there's strong need I'll probably keep without it.  I like the flexibility of not having a license. There has been cases where people uploaded Global Speed but with additional code that added an Amazon link referral to all purchases. I was able to request the store to take it down because it used my source code. If I had a license, I don't think I would've been able to do anything.

**Comment by andreyplus** [comment]
@polywock Thanks for your response. I do think a fitting license is always possible, but of course, the final call is yours.
