### ISSUE TITLE
作者您好，能否做网络配置同步的功能，接入一下Googledrive

### ISSUE THREAD

**Issue by shiyuanGame** [polywock/globalSpeed#255]
能否做网络配置同步的功能，接入一下Googledrive  我的设备比较多 手动设置后同步起来比较麻烦

**Comment by polywock** [comment]
Hi. Due to a MV3 migration issues, progress on Global Speed pretty much stalled for 2 years. Although, I would love to implement sync, it's not looking great.

I'm about done with the upgrade, but I decided against sync for a few reasons. The new structure of Global Speed requires fast storage read/writes. I've ran benchmarks and the sync storage space is 5x slower which makes it less than ideal. Although, I did try working around it, however that introduced too much complexity.

I'll shelve the feature for now, but hopefully if new proposals like onChanged filters get implemented by the browsers, I could look into implementing it again.
