### ISSUE TITLE
非常希望添加以網頁全屏模式播放的功能（含auto toggle開關） 

### ISSUE THREAD

**Issue by kakushou** [polywock/globalSpeed#274]
就是B站的那種網頁全屏大小模式 🤝  謝先！！！

**Comment by polywock** [comment]
Hi. It's possible to do but kind of complicated. 

1. Turn on  "capture" (捕获) in the audio effects section. This is normally used for audio effects, but also helps with bilibili style fullscreen. 

2. Enter fullscreen mode on any website. For some websites, nothing happens after entering fullscreen mode, you have to resize the window. 


![a1](https://user-images.githubusercontent.com/31208859/196260881-45a33e9c-ff54-41db-9883-f40b3616fdea.png)


Image 2
![a2](https://user-images.githubusercontent.com/31208859/196260888-cd88507f-72a4-466b-995d-377cc8d028bf.png)


It's kind of complicated so I'll try to explain the process. This extension uses the `Tab Capture API` for audio effects like pitch shift, volume boost, etc. The Tab Capture API is an API for Chrome and Edge that can be used to listen and manipulate the page's audio.  This API has two limitations because of privacy concerns. First, once an extension captures a tab's audio, the browser wants the user to know their tab's audio is being captured, so they show a small indicator over the tab like this. 

![main](https://user-images.githubusercontent.com/31208859/196256740-654f9eb3-19b8-4dcb-ab84-cb36d15920e0.png)

The browser wants the user to always see this little blue indicator. Because of this, if the tab's audio is captured, you cannot enter normal fullscreen mode. If you try to enter fullscreen mode while tab's audio is captured, it will go half fullscreen like Bilibili. On websites, it acts glitchy and you have to resize the browser window to make it work.

**Comment by kakushou** [comment]
這個方法太繁瑣且看上去不太可靠 😅 just want  function like this extensions  

https://chrome.google.com/webstore/detail/youtube-windowed-fullscre/gkkmiofalnjagdcjheckamobghglpdpm

**Comment by polywock** [comment]
Hi. Although it seems unreliable, it's actually the best method I found so far thats works on all websites. You can even setup a shortcut key for convenience. In the Global Speed options page, create a Capture (捕获) shortcut key and set the shortcut key to whatever you like. 

![img2](https://user-images.githubusercontent.com/31208859/197305005-b8d04497-3d67-4b9f-9817-ef8eb8437f6c.png)

![img3](https://user-images.githubusercontent.com/31208859/197305010-514083a2-074c-45ee-913a-103b125713d4.png)


Anytime you want to enter Bilibili style fullscreen, just trigger the shortcut, and press the normal fullscreen button. It works flawlessly on most websites like Youtube, Bilibili, pan.baidu.com, etc.. On some websites, nothing happens after entering or leaving fullscreen. If that happens, just resize the window a little.
