### ISSUE TITLE
进入视频网站后会提示“刷新页面以使用此扩展”

### ISSUE THREAD

**Issue by guodaipi** [polywock/globalSpeed#288]
[每次观看视频打开网页时插件总会提示刷新页面以使用此扩展，必须点击刷新后才可以正常使用

**Comment by polywock** [comment]
Hi. You probably have Global Speed set to run only when you click the extension. Global Speed is not designed to be run this way so that's why it asks to refresh page. To fix, change it so that it run on specific websites or all websites. 

![issue](https://user-images.githubusercontent.com/31208859/203673059-29069a7e-85b2-4bb7-b88a-2348c2433a07.png)
