### ISSUE TITLE
web-wide failure

### ISSUE THREAD

**Issue by ymorsi7** [polywock/globalSpeed#303]
extension no longer working on all sites - Google Chrome

**Comment by polywock** [comment]
Hello. Problem caused by 2.9.991 update. Should be fixed in 2.9.992, but update might take a day to get approved.  

Here's the fixed version if you want to load it manually for now. 

[packed.zip](https://github.com/polywock/globalSpeed/files/10251706/packed.zip)

1. Download packed.zip and extract the folder. 
2. open extensions page, chrome://extensions 
3. Disable the original Global Speed. 
4. Enable dev mode in top right of page. 
5. Click "load unpacked" in top left of page and load the folder.

**Comment by ymorsi7** [comment]
Solid, thanks!
