### ISSUE TITLE
Negative audio delay/Video delay functionality

### ISSUE THREAD

**Issue by qb20nh** [polywock/globalSpeed#309]
This is useful when using bluetooth audio with high latency

**Comment by polywock** [comment]
For Youtube, you can try this [extension](https://chrome.google.com/webstore/detail/youtube-audiovideo-sync/mknmhikmjljhpccebpnplhicmcfjkgbk). It mutes the Youtube video, and loads a separate audio only stream with the time position shifted. This is the only practical approach for negative audio delay I found that works so far, but it's hard or even impossible to extend to other sites. 

B&H has products available for delaying audio signals. But, they can cost thousands of dollars. 

https://www.bhphotovideo.com/c/buy/Video-Delays/ci/5721/N/4028759659

**Comment by qb20nh** [comment]
I'll open this again when its viability is shown with a working example.

1. "Clone" the active video element
2. Sync cloned video element's progress with the original with delay
3. Show cloned video just over the original video element, transparent to the pointer and keyboard

All these steps will likely break many websites.

**Comment by polywock** [comment]
> All these steps will likely break many websites.

Pretty much. But, a similar method might work. 

The third step seems unnecessary. If you can clone the video, you could just mute the original, and keep the clone hidden with audio playing.  The problem will be cloning the video. It would only work with simple videos that are linked to static video files on the internet. Like this for example. 

https://storage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4

But. most video streaming sites have complex systems for loading/stitching video segments. Cloning will require investigating/reverse engineering each website individually to understand how they load the video. 

Even with this, it would be inefficient because it will double the bandwidth cost (loading two videos). 

A similar idea I had was instead of cloning the video. Why not clone the tab. The primary tab with the video will be muted. The second tab will be playing audio with time position shifted for your desired delay. If you pause the video on the primary tab, the extension will pause the video on the second tab. The role of the extension will be to keep the video synced (with delay of course).
