### ISSUE TITLE
Indicator shows multiple actions at the same time

### ISSUE THREAD

**Issue by liangjiancang** [polywock/globalSpeed#31]
For example,

![111](https://user-images.githubusercontent.com/42267675/90324432-6a0a2580-dfa1-11ea-82c8-9274d436414c.png)

When you press ^Numpad5，the indicator just shows the second action `100%`. I think this is better:

![2222](https://user-images.githubusercontent.com/42267675/90324525-80fd4780-dfa2-11ea-9a83-c3ace0366bd9.png)

**Comment by polywock** [comment]
We have similar thought processes. I did actually implement that. But, reverted the changes because...

1. Unlikely the user would configure two actions with the same shortcut key.

2. It didn't look very good (clutter, animation didn't always sync, some combinations didn't look good together).

3. Collision: many shortcut keys have very similar indicator text.
