### ISSUE TITLE
在edge浏览器的芒果TV官网失效

### ISSUE THREAD

**Issue by ShenLanD** [polywock/globalSpeed#316]
在edge浏览器的芒果TV官网使用失效，倍速没有反应，点按扩展也不出现应用到mgtv.com网站，在其他浏览器正常

**Comment by ShenLanD** [comment]
![示例gif](https://user-images.githubusercontent.com/105553213/211779082-85120875-58c3-4f91-9b7e-23f328bc922c.gif)

**Comment by polywock** [comment]
Hello. Mango TV works for me on Chrome/Edge, but on Mac. It might be a Windows Edge issue. 

1. Since there are many lookalike extensions. Confirm you have the official one here. 

https://microsoftedge.microsoft.com/addons/detail/global-speed/mjhlabbcmjflkpjknnicihkfnmbdfced

2. Try turning on Ghost mode in the options page. This should stop websites from resetting speed back to 1x. If that didn't work continue to next step. 
 
3. Reinstall Global Speed on Edge. Sometimes this fixes the issue. If not continue to next step. 

4. Check to see if it's a VIDEO element or a CANVAS element. Some domestic 🇨🇳  websites use CANVAS element to play videos which makes it incompatible with Global Speed. Go to Mango TV video page and press CTRL-SHIFT-C and then 

5. Some websites add DRM to videos when using Windows + Edge. Go to `edge://flags` and search "PlayReady DRM" and disable it. Restart Edge and check if the Mango TV works now. If that didn't work, re-enable PlayReady DRM.

**Comment by ShenLanD** [comment]
> 你好。Mango TV在Chrome / Edge上为我工作，但在Mac上。这可能是 Windows Edge 问题。
> 
> 1. 由于有许多相似的扩展。确认您在此处拥有官方版本。
> 
> https://microsoftedge.microsoft.com/addons/detail/global-speed/mjhlabbcmjflkpjknnicihkfnmbdfced
> 
> 2. 尝试在选项页面中打开幽灵模式。这应该会阻止网站将速度重置回 1 倍。如果这不起作用，请继续下一步。
> 3. 重新安装边缘上的全局速度。有时这可以解决问题。如果没有，请继续下一步。
> 4. 检查它是 VIDEO 元素还是 CANVAS 元素。一些国内🇨🇳网站使用 CANVAS 元素播放视频，这使得它与全球速度不兼容。转到芒果TV视频页面并按Ctrl-SHIFT-C，然后四处寻找VIDEO元素或CANVAS元素。如果您看到画布，请告诉我。
> 5. 某些网站在使用Windows + Edge时将DRM添加到视频中。转到并搜索“PlayReady DRM”并禁用它。重新启动 Edge 并检查芒果电视现在是否正常工作。如果这不起作用，请重新启用 PlayReady DRM。`edge://flags`

Thank you very much for your reply, I fixed this issue by updating the Edge browser.
