### ISSUE TITLE
URL rules for sound control

### ISSUE THREAD

**Issue by liangjiancang** [polywock/globalSpeed#32]
There is only `state`, `speed` and `filter` now.

**Comment by polywock** [comment]
I will try to implement that. But, the `TabCapture API` (used to manipulate the tab's audio) requires the user first invoke that extension for that tab. So, the user would still need to click the "capture" button, or use the "capture" shortcut (in global mode, local mode isn't sufficient to invoke the extension) 

Unlike speed or filters, I cannot make it truly convenient.

On a side note, can you email me at `polywockhelp@gmail.com`, I want to ask for a few words/phrases translated. Thank you.

**Comment by liangjiancang** [comment]
If necessary, you can email me at `liangjiancang@foxmail.com`.

**Comment by polywock** [comment]
Thank you. I've redacted your email, just in case (bots and what not).

**Comment by WarriorONeal** [comment]
I think this goes best into this sub thread:

If you can create controls for multiple URLs independently, maybe take a look at the chrome version from this speed controller called: Video Speed Controller (https://chrome.google.com/webstore/detail/video-speed-controller/nffaoalbilbmmfgbnbgppjihopabppdk) there, without any options to change it to my knowledge you have a speed controller for every independent url by default.

**Comment by polywock** [comment]
@WarriorONeal  Have you tried enabling the "pin by default" setting in the option page? This would automatically pin 📌 all new tabs. That way each tab can have different speed values. This is would make the experience more similar to Video Speed Controller.

**Comment by WarriorONeal** [comment]
@polywock yes, after using the "pin by default" setting, it worked as you have stated.

I went through your FAQ before asking here on GitHub and would have never thought that "pin by default" would talk about the thing i was looking for. Maybe you could change up the wording of the setting a bit. 

You can still include the "pin by default" phrase with its info box, because who knows what this setting can do else, but you can add things like: " It will allow you have the speeds, sounds, etc adjusted on a per webpage basis (or on each website separately)".
Because even after I have first downloaded your extension, I did not know what that setting meant.

Thank you for the help!

**Comment by polywock** [comment]
@WarriorONeal No problem, thanks for the feedback. Yeah, the UX design could use some work. I'll work on improving the FAQ section soon. Maybe also create video tutorial.
