### ISSUE TITLE
Should ignore YouTube live videos (and other live streaming)

### ISSUE THREAD

**Issue by cliffordp** [polywock/globalSpeed#327]
During YouTube live streaming (not typical YT on-demand video), when on a speed higher than 1 (e.g. 2.5), it cuts out because it's waiting for the live feed to come through then plays it at 2.5x

**Comment by george-atsushi-ehara** [comment]
I got this to work for Twitch since the URL is unique but the YouTube live URL is not distinct with VODs

1. Scroll to URL Rulles
2. Select Create
3. Select the `-- # --` to make a new rule
4. Change `contains` to `regex`
5. Input this into the text box `/^(?:twitch\.tv\/videos\/\d+|twitch\.tv\/.*\/clip\/.*)$/i`

This will make any VOD urls like Past live Stream and Clips use 
I only did a minor test on this but it seems to work the only problem is that regardless of you turn on or off ILO or LAX the live section will initially start off really fast for like one or two seconds so there will be an audio desync but it will maintain a 1x speed

**Comment by polywock** [comment]
Hello. Apologies for the late reply. Going through the old issues one by one. As of today, this feature is not supported and probably won't be. Detecting live videos on sites like Youtube require CSS/HTML detection which is hard to do efficiently. Additionally, some users want the speed to work on live videos. For those reasons, I'll close this issue.
