### ISSUE TITLE
【默认音量记忆】

### ISSUE THREAD

**Issue by Ushnidaye** [polywock/globalSpeed#331]
现在插件不能自动记忆上次手动调节后的音量速度设置，而是只能机械地使用系统默认的设置，建议改成新播放的流媒体适用上次用户调节的最新设置

**Comment by polywock** [comment]
Hello. This is suggested often, but it's difficult to find a balanced solution. Users want to use the video's audio slider. Users also want to memorize speed. These two are conflicted with each other in practice. Global Speed can store the last volume and set it for each new video, but the website often resets volume to what it thinks is the ideal volume during certain events (video loaded, video paused, every 10 seconds, etc). You can stop websites from doing that, but the video's audio slider will also stop working. Each implementation I've offered to users in the past had drawbacks. 

I will look into providing an optional feature where volume is memorized, I will have to warn them that they will only be able to change volume through Global Speed's audio shortcuts. Otherwise, they will think something is broken.
