### ISSUE TITLE
Conflict with wGesture

### ISSUE THREAD

**Issue by jiang-yuan** [polywock/globalSpeed#338]
wGesture is a Mouse gesture software.
1. I set press c to increase the video speed by 0.1
![image](https://user-images.githubusercontent.com/36291537/221579355-8ac49138-7ebf-4b9c-a5da-fd204ee92861.png)
2. In wGesture, I specify 'press down the right click of mouse and scroll down the wheel' map to 'volume down' key
![image](https://user-images.githubusercontent.com/36291537/221580009-e80b08f4-f1b3-4e38-a1f3-ff8b8a376f8e.png)
3. Every time I press down the right click of mouse and scroll down the wheel, the volume go down and the video speed increase by 0.1 at the same time
![image](https://user-images.githubusercontent.com/36291537/221580441-2f0c0742-df47-493f-839e-66efeabf4b5e.png)
I try to disable shortcut 'c' in globalspeed, the video speed will not change as above.
I also try to only press volume down button on my keyborad, the video speed will not change as above.

This problem only happens when I set up the mouse gesture and c to increase the video speed by 0.1 .

**Comment by polywock** [comment]
Hello. To test whether the issue is Global Speed. Try disabling Global Speed and going to one of these websites that tell you which key is being pressed. Once you go there, try doing the mouse gesture to see if C is detected. If C is detected, it means wGesture has an issue. 

https://www.toptal.com/developers/keycode 

https://keycode-visualizer.netlify.app/

**Comment by polywock** [comment]
Hello. It seems like wGesture has a bug that triggers C key. Should report the issue to the developers. 

https://github.com/yingDev/WGestures/issues
