### ISSUE TITLE
百度网盘失效，获取视频失败

### ISSUE THREAD

**Issue by lzh-zone** [polywock/globalSpeed#376]
百度网盘失效，获取视频失败

**Comment by polywock** [comment]
Usually when Baidu network disk fails, a lot of people complain. Since it's pretty quiet, the issue might be caused by a conflicting extension, or another problem that's only affecting you. 

1. Try disabling Global Speed and checking if the issue still persists.  If the issue only happens with Global Speed enabled, move on to the next step. 
2. Try disabling all extensions except Global speed to see if an extension is conflicting with Global Speed. 
3. Try reinstalling Global Speed.
