### ISSUE TITLE
LMS365

### ISSUE THREAD

**Issue by Wang-MK** [polywock/globalSpeed#377]
Extension doesn't seem to work on LMS365 videos. Hopefully there is a way around it.

Digging through the source code gives a script link for the player, not sure if it helps.
https://ca-assets.365.systems/assets/js/player?v=CrQA2tPRQAz96Y4NNDZSRy94iH84uqHVWaRW5J3lgug1

**Comment by polywock** [comment]
Have you tried enabling Ghost mode (幽灵模式) in the options page?

**Comment by Wang-MK** [comment]
Yes, still doesn't work with ghost mode. =(

**Comment by polywock** [comment]
Is there a way for me to test LMS365 videos? On the website for LMS365, the demo videos just look like Youtube embeds. 

https://lms365.com/videos/

**Comment by Wang-MK** [comment]
Unfortunately I don't think there is an easy way to get a trial without a
bunch of info. I also feel like it depends on how the course is implemented
as it seems like it uses a multitude of different players, some of which
global speed does work, and some that it doesn't.

I guess it's not too big of a deal and I can live with the few videos that
I'm forced to watch at normal speeds.

Thanks for prompt response, the extension is amazing. Keep up the good work.

Regards,
Michael

**Comment by polywock** [comment]
Thank you for the kind words. Although, I cannot test for sure, I do have some theories.  

1. I've so far encountered only a few websites that Global Speed doesn't work on, many of them Chinese streaming sites that use the CANVAS element to play videos instead of the conventional VIDEO element. They do this to save on data costs as with canvas they can play unsupported codecs like HEVC. Maybe it's the case here as well. Although, there's nothing I can do if turns out to be the case, you can right click the page and click "Inspect" to check if the video is actually a VIDEO element, or if it's a CANVAS element.  

2. Another thing I've encountered is some users change permissions of Global Speed to a particular website, or to "When you click on the extension". This restricts Global Speed from running on embedded videos.
