### ISSUE TITLE
靜音的分頁暫停撥放？

### ISSUE THREAD

**Issue by Apple-Huang** [polywock/globalSpeed#381]
LINE TV ：
https://www.linetv.tw/feed/campaign?source=NAVBAR

設定：
![2023-06-18_142619](https://github.com/polywock/globalSpeed/assets/43962513/3e815cd2-5056-4580-b276-bb2926eb1870)

我使用 Edge 瀏覽器觀看 LINE TV 賺點任務裡面的劇，
在多個背景分頁同時觀看不同連結的情況下，部分分頁有時候會出現「自動靜音」的情況。
困擾的是，這些靜音的分頁在背景是處於暫停撥放影片的狀態。
唯有用滑鼠點擊他們將其從背景分頁切換至當前分頁，或手動取消該戲劇靜音狀態，他們才能執行我所設定的倍速撥放。

**Comment by polywock** [comment]
Unfortunately I cannot test it myself as LINE TV is region locked. 

Maybe the website is detecting multiple streams and is pausing/muting as a result. 

This probably won't help, but you could try enabling Ghost mode in the options page. This mode prevents websites from changing the speed and makes the video appear to be playing at normal speed. If the website is indeed pausing or muting because it detects the video is set to a higher speed, this might just do the trick.

Sorry that I can't be of more help.
