### ISSUE TITLE
反馈指示器里的全屏是什么意思呀？

### ISSUE THREAD

**Issue by zjh16** [polywock/globalSpeed#398]
1. 反馈指示器里的全屏是什么意思呀？
2. 按键那一部分  全屏后面的简单模式是什么？
3. 希望作者出一份教程~~嘻嘻，那些按钮有些看不懂，而且更高级的玩法，普通人也很想尝试

**Comment by polywock** [comment]
Hi. The fullscreen shortcut enters fullscreen. Sometimes websites let you press F to enter fullscreen, but some websites don't. Overall, it's not consistent. That's why I implemented a fullscreen shortcut key. It has two modes. 

Fullscreen (simple/native mode): Enters fullscreen mode directly on the video and activates the HTML5 native controls. This is a unique approach to fullscreen. The original controls/subtitles/barrage will be hidden and the video alone will be in fullscreen mode.  

Fullscreen (standard mode): tries to enter fullscreen mode on the container element to mimic the website's standard fullscreen behavior. This method requires learning. If you visit a new website, you must manually click on the fullscreen button at least once. Otherwise, Global Speed won't know which element is the video player container.

Note: the fullscreen hotkey is buggy on some websites.


I'm too lazy to write a guide 😫 But, let me know if you have questions about specific features. I will be happy to answer them.

**Comment by zhangjunhui16** [comment]
> 你好。全屏快捷方式进入全屏。有时网站允许您按 F 进入全屏，但有些网站不允许。总的来说，它并不一致。这就是我实现全屏快捷键的原因。它有两种模式。
> 
> 全屏（简单/纯模式）：直接在视频上进入全屏模式并激活 HTML5 原生控件。这是一种独特的全屏方法。原始控件/字幕/弹幕将被隐藏，视频将单独处于全屏模式。
> 
> 全屏（标准模式）：尝试在容器元素上进入全屏模式，以模仿网站的标准全屏行为。这种方法需要学习。如果您访问新网站，则必须至少手动单击一次全屏按钮。否则，全局速度将不知道哪个元素是视频播放器容器。
> 
> 注意：全屏热键在某些网站上有问题。
> 
> 我懒得写指南😫但是，如果您对特定功能有疑问，请告诉我。我很乐意回答他们。

Thanks to the author, your reply is very helpful to me, I have another question, what does the fullscreen check box mean (its location is in: Options- > indicator)

**Comment by polywock** [comment]
Short version: I made "fullscreen" optional because it might cause bugs on some websites. 

### Long version
When I first added the feedback indicator, users complained that it doesn't show when in fullscreen mode. That's because I attached the indicator directly to the page root. This is usually the best approach because it doesn't interfere with the website's structure. However, when the user goes fullscreen everything outside the video container is hidden (including the feedback indicator). 

To work around this issue, I move the feedback indicator into the video container when the user goes fullscreen. That's the only way to make it visible during fullscreen mode. This is usually fine, but it may cause issues on some websites depending on how the website was coded. For example, the developer of the website might grab the first element which he knows is the pause button. But, if the user installed Global Speed. The first element will now be the feedback indicator. So the website has a conflict with Global Speed. This is why I made "fullscreen" optional because it might cause bugs on some websites.

**Comment by zhangjunhui16** [comment]
> Short version: I made "fullscreen" optional because it might cause bugs on some websites.
> 
> ### Long version
> When I first added the feedback indicator, users complained that it doesn't show when in fullscreen mode. That's because I attached the indicator directly to the page root. This is usually the best approach because it doesn't interfere with the website's structure. However, when the user goes fullscreen everything outside the video container is hidden (including the feedback indicator).
> 
> To work around this issue, I move the feedback indicator into the video container when the user goes fullscreen. That's the only way to make it visible during fullscreen mode. This is usually fine, but it may cause issues on some websites depending on how the website was coded. For example, the developer of the website might grab the first element which he knows is the pause button. But, if the user installed Global Speed. The first element will now be the feedback indicator. So the website has a conflict with Global Speed. This is why I made "fullscreen" optional because it might cause bugs on some websites.

What is Hidden Media List

**Comment by polywock** [comment]
By default, Global Speed shows a list of video and audio on the current tab. 

![mediaList](https://github.com/polywock/globalSpeed/assets/31208859/a067ab53-b830-425b-b56b-a87086b78fad)

***
The primary use case is to control which video is prioritized for Global Speed's shortcut keys. For example, if you're listening to background music. You can press the mouse cursor to select that audio element. You can now go to different tabs and still control the music. If you enable global shortcut keys, you can even control music while using a different application. 

![select](https://github.com/polywock/globalSpeed/assets/31208859/eaf0e244-4b2f-4bf7-a727-51cc36d56e7a)
