### ISSUE TITLE
哔哩哔哩视频报错

### ISSUE THREAD

**Issue by kuronekoda** [polywock/globalSpeed#400]
![image](https://github.com/polywock/globalSpeed/assets/136661812/f32d60fa-9603-41c4-ae77-910979888c98)
删除拓展重新添加也没用

**Comment by polywock** [comment]
Hi. Interesting issue. Same [video](https://www.bilibili.com/video/BV1Dp4y1V7yC) works for me. 

1. What's your OS and browser version? 

2. Does this also happen on other websites? 

3. Can you right click to the right of the "An error occurred" message and click "Inspect". A window should open with a "console" tab. Open that tab and let me know if there is any error message (should be red). 

4. Does it also happen on the options page? 

Chrome: chrome-extension://jpbjcnkcffbooppibceonlgknpkniiff/options.html

Edge: extension://mjhlabbcmjflkpjknnicihkfnmbdfced/options.html

**Comment by kuronekoda** [comment]
![0f92a866301180753e10baee65e22402](https://github.com/polywock/globalSpeed/assets/136661812/390fc76a-ec43-4a89-8486-ec5e9baea3ac)

![image](https://github.com/polywock/globalSpeed/assets/136661812/26c8b351-a1df-4c37-8514-71a4654a2256)
![image](https://github.com/polywock/globalSpeed/assets/136661812/7035e919-64a2-426b-8ad4-ffa79a2380a0)

**Comment by kuronekoda** [comment]
> ![0f92a866301180753e10baee65e22402](https://user-images.githubusercontent.com/136661812/258054368-390fc76a-ec43-4a89-8486-ec5e9baea3ac.png)
> 
> ![image](https://user-images.githubusercontent.com/136661812/258054322-26c8b351-a1df-4c37-8514-71a4654a2256.png) ![image](https://user-images.githubusercontent.com/136661812/258054565-7035e919-64a2-426b-8ad4-ffa79a2380a0.png)

似乎无法在我的edge中运行

**Comment by kuronekoda** [comment]
![image](https://github.com/polywock/globalSpeed/assets/136661812/66094a9b-6891-44bf-9154-2a006b63ad99)
![image](https://github.com/polywock/globalSpeed/assets/136661812/ed1d1072-77fc-4cbe-936f-328f7f1a585f)
![image](https://github.com/polywock/globalSpeed/assets/136661812/ae840d6d-57ba-4442-a792-4f30ce36f0f4)
似乎无法在我的edge上运行，不看视频时可以打开界面，但是点击设置或者别的就会报错用不了

**Comment by polywock** [comment]
Hello. Thank you for the screenshots. I will investigate the issue. I suspect it has something to do with the media list because you said it only opens when no video is playing. If so, you can try opening the options page.  

extension://mjhlabbcmjflkpjknnicihkfnmbdfced/options.html 

And enabling "hide media list" (隐藏媒体列表).

**Comment by kuronekoda** [comment]
There is a problem with the translation, when I am not watching the video, the interface can open, but click on the settings, sound or play the video he will report an error, and I cannot open your link, the URL shows edge to block me from accessing
![image](https://github.com/polywock/globalSpeed/assets/136661812/1da1a5ac-5955-4f39-815a-c8e2c6eccf40)
![image](https://github.com/polywock/globalSpeed/assets/136661812/cbc6db9e-456e-4455-aa41-9a9b45fbe4ba)
![image](https://github.com/polywock/globalSpeed/assets/136661812/a96acd0c-3404-4c6a-98b1-a18e218d1e04)

**Comment by kuronekoda** [comment]
After reporting the error, even if I don't watch the video, it can't be opened, only if I restart Edge, reopen it in the extension can show the interface, after restarting Edge it can't do anything, do everything wrong, delete the extension and reinstall is still the same, press refresh and reset after the error can not do anything

**Comment by polywock** [comment]
Understood. Since you're the only person to report this issue, it might be related to your environment. We can test this out. 

1. Does Global Speed work on a new Edge profile? Each Edge profile has isolated extensions, cache, so is useful tool for debugging environmental factors. 

edge://settings/profiles 

You can go here, and on the top-right click "Add profile". Once you switch to that profile, install Global Speed to test it out. 

2. Are you the type of person to tinker around with experimental browser flags? Some change might have conflicted with Global Speed. If so, you can try pressing Reset All on edge://flags. 

3. If the first two still didn't have any impact, you can also loading this "special" Global Speed. Which should print to console a more useful error message. Might not be worth the effort, but I'll leave it anyway. 

[packed.zip](https://github.com/polywock/globalSpeed/files/12251248/build.zip)

1. Download packed.zip and extract the folder. 
2. open extensions page, edge://extensions 
3. Disable the original Global Speed. 
4. Enable dev mode on the left panel of the page. 
5. Click "load unpacked" in top right of page and load the folder.   

Once you get that "An error occurred" message again, right click to inspect, and open console tab to check for the error message.

**Comment by kuronekoda** [comment]
Thank you, by resetting the Edge browser is already available globally![image](https://github.com/polywock/globalSpeed/assets/136661812/c5d5716c-1be5-443b-9a59-38deedc548d9)

**Comment by polywock** [comment]
Nice. Let me know if the problem reappears.
