### ISSUE TITLE
hevc支持

### ISSUE THREAD

**Issue by weineo** [polywock/globalSpeed#401]
目前chrome系浏览器已全面支持hevc，能否放开对于hevc的限制呢😊

**Comment by polywock** [comment]
Hello. I don't place any restrictions of HEVC. Many websites like Bilibili used to play HEVC videos through a non-standard player, which made it incompatible with Global Speed. To workaround this for Bilibili, I used to block HEVC mode on Bilibili so that Bilibili used a different codec. Now that Chrome supports HEVC, Bilibili has switched to using the normal Video element. Bilibili with HEVC is now compatible with Global Speed.  But, to play HEVC videos, some websites are still using a non-standard player so they're still not supported. I do not support non-standard players. They often use WASM/Canvas and are extremely complicated to support.
