### ISSUE TITLE
有些网站不支持倍速播放 比如抖音 QQ小世界

### ISSUE THREAD

**Issue by Monster-DP** [polywock/globalSpeed#408]
有些网站不支持倍速播放 比如抖音 QQ小世界
https://www.douyin.com/
https://xsj.qq.com/

**Comment by polywock** [comment]
Have you tried enabling "ghost mode" in the options page? For me, both websites work, even without ghost mode.

**Comment by Monster-DP** [comment]
> Have you tried enabling "ghost mode" in the options page? For me, both websites work, even without ghost mode.

开启幽灵模式就OK了 成功解决 ❤️❤️😘😘

**Comment by polywock** [comment]
Weird.  I figured out the reason. They're sometimes playing videos using a \<canvas\> element instead of a \<video\> element. Canvas is not a video player, it's a graphics API which is often used for games. But, some websites use it to play videos.It's hard to support such websites as they each require a personalized solution. 

![sc](https://github.com/polywock/globalSpeed/assets/31208859/105c387b-a916-4f24-adbb-f1c14d08441e)
