### ISSUE TITLE
在edge和chrome中使用时快捷键都无法正常使用

### ISSUE THREAD

**Issue by AlexanderCyril** [polywock/globalSpeed#415]
edge 117.0.2045.43 (正式版本) chrome117.0.5938.92（正式版本)
最近扩展的快捷键都不起作用了,试了几次也没有找到原因

**Comment by polywock** [comment]
Hello. The shortcuts still work for me on both Edge and Chrome. Have you tried resetting the extension by going to the very bottom of the options page? If that doesn't work, try to reinstall the extension. Let me know if these don't fix the issue.

**Comment by cz159888** [comment]
重新安装了插件也不行，感觉是最近一次win11系统更新导致的

**Comment by polywock** [comment]
I don't currently have access to a Windows 11 device so can't test for myself, so will have to bother you with a few questions. 

1. Where did you install Global Speed, and which version is it? 
3. Does changing speed through the toolbar menu work?  
4. What happens when you press a shortcut key, if anything. 
5. If you right click the page and press "Inspect", and go to console tab. Do you see any errors, especially when you press a shortcut key?

**Comment by AlexanderCyril** [comment]
Thank you very much for your work and reply!
I tried reinstalling the extension but that didn't work. It worked for a short time but then it didn't work again.

1 The version of the extension is 2.9.996 and I am using Win11 22621.2283.
2 Everything works fine except for the shortcuts, and changing the speed via the toolbar menu works.
3 When I press the shortcut key there is no display or reaction.
4 When I press the shortcut key check page chrome shows two problems
    1)document.domain mutation is ignored because the surrounding agent cluster is origin-keyed.
    2)[Vue warn]: Avoid app logic that relies on enumerating keys on a component instance. The keys will be empty in production mode to avoid performance overhead.
5 Checking the page edge when pressing the shortcut key shows a similar problem:
    [Vue warn]: Avoid app logic that relies on enumerating keys on a component instance. The keys will be empty in production mode to avoid performance overhead.

I'm not very familiar with the functional use of "Inspect"I'm not sure if this is the response you were hoping for.
Thanks again for your work!

**Comment by polywock** [comment]
Thanks, that's helpful. The extension doesn't use Vue, so the error is coming from the website. It might not be related, or that website has a conflict with Global Speed. Does shortcuts work on different websites?

**Comment by polywock** [comment]
@OthuMMMM Is this issue on all websites?

**Comment by OthuMMMM** [comment]
Yes.  I tried it on different websites and different divice,  shortcuts just didn't  work.

**Comment by AlexanderCyril** [comment]
Sorry for my late reply, I have tried many video web pages, but the shortcut keys do not work

**Comment by polywock** [comment]
This is a weird issue. Some of my thoughts. 

1. The extension, by itself is not to blame, as the issue was first reported when the extension hasn't been updated in 5 months. 
2. It's only impacting a small amount of people, otherwise there would've been more feedback. 

For these reasons, I suspect there is a conflict with another extension or userscript. 

@AlexanderCyril, @OthuMMMM, can you guys test this theory out by disabling all your extensions except Global Speed? Make sure to refresh your page afterwards, and check if shortcuts now work.

**Comment by AlexanderCyril** [comment]
I had previously suspected that it was due to other extension conflicts, but after disabling the other extensions, my shortcut keys still didn't work T_T

**Comment by polywock** [comment]
@AlexanderCyril Too bad. Have you also tried creating a new Edge profile and trying Global Speed there? This is a good test because a new profile will have separate environment (no extensions, cache, etc).  If this doesn't work, I will try getting access to a Windows 11 machine. 

edge://settings/profiles

![screen1](https://github.com/polywock/globalSpeed/assets/31208859/0b7b89e6-2287-4ef0-ab3f-67d5b68b9014)
![screen2](https://github.com/polywock/globalSpeed/assets/31208859/cbb7ea28-522a-4dfb-9efd-cffd1afbcf5b)

**Comment by AlexanderCyril** [comment]
@polywock  Thank you very much for your advice and patience, I tried the new configuration file, which is similar to the result of uninstalling and re-installing the extension, the re-installation worked properly for the first time, and the shortcut key did not work after closing the browser. Maybe this is just a problem on my machine, adjusting the speed in the menu page can also be used normally. Sorry to bother you for a while. Thank you again for your help!

**Comment by AlexanderCyril** [comment]
Hello, today after I updated the win11 system, the shortcut key function is all back to normal. The version number is 22621.2361, thank you!

**Comment by polywock** [comment]
@AlexanderCyril Great. thanks for the update. It seems like it was a bug with Win11 or Edge.

**Comment by polywock** [comment]
@AlexanderCyril Hello, again. Another user reported the 小狼毫 input method doesn't work with Global Speed. Do you use this input method? I want to make sure they're unrelated.

**Comment by AlexanderCyril** [comment]
> @AlexanderCyril Hello, again. Another user reported the 小狼毫 input method doesn't work with Global Speed. Do you use this input method? I want to make sure they're unrelated.

Hello! I'm sorry I haven't checked my email lately. I have not used the小狼毫 input method you mentioned. 
The issue of input methods affecting shortcuts does exist, but it should only be language related. 
In the use of Chinese input method is not able to use the shortcut button, switch to English input method or lock the uppercase button can be used normally.
