### ISSUE TITLE
[Bug] 使用小狼毫输入法无法在中文输入法状态下, 通过快捷键调整播放速度

### ISSUE THREAD

**Issue by doit132** [polywock/globalSpeed#434]
# 测试环境

- 输入法软件 
  - windows 小狼毫输入法
  - QQ 输入法
  - 手心输入法
- 版本 Windows 11 专业版
- 版本 23H2
- 操作系统版本 22635.2700
- 测试浏览器
  - edge 浏览器
  - chrome 浏览器
  - firefox 浏览器
- 测试网站
  - 目前没有发现什么视频网站, 可以使用按键来调速的 (在小狼毫中文输入法状态下)
 

# 测试结果

- 小狼毫输入法
  - 在中文输入状态下, 只有 firefox 浏览器可以通过按键的方式修改播放速度
  - 在英文输入状态下, 三个浏览器都可以通过按键的方式修改播放速度
- 其他两个输入法不会出现这种情况, 即使在中文输入状态, 也可以正常通过按键修改播放速度

**Comment by polywock** [comment]
Interesting. I tried on Mac and it seems to work fine. Maybe it's a Windows only issue. 

Has this always been an issue, or is it recent?

**Comment by doit132** [comment]
> Interesting. I tried on Mac and it seems to work fine. Maybe it's a Windows only issue.
> 
> Has this always been an issue, or is it recent?

大概率是输入法自身的问题, 我使用的是 https://github.com/Techince/weasel/releases/tag/weasel-0.15.1.0_x64 这个版本的小狼毫, 请忽略这个 issue 吧

**Comment by polywock** [comment]
I tried the Mac version (Squirrel) with no issues. With that input method (小狼毫), do shortcuts get registered in the options page?  

![Screenshot 2023-11-07 at 12 25 28 AM](https://github.com/polywock/globalSpeed/assets/31208859/8f650fcb-0504-49f0-b4c1-64eefebe980b)

**Comment by Carrotist** [comment]
I also have the same problem

**Comment by Carrotist** [comment]
@polywock   I ‘m a student form China and I have been confused by this problem for a quite long time, under Windows environment.  
##Test Environment
*****
-System: Windows 11 23H1 ("Family Chinese Version( 家庭中文版 )")
-Test Browser: Edge (**Global Speed downloaded from Edge Addons**)
-Test Website: Mainly Bilibili
-Trigger probability: almost always
##Used input method
*****
  -Some are able to use under the Chinese mode
    1.微软输入法（microsoft's ）
    2.微信输入法（wechat's）
  -Some are **unable** to use under the Chinese mode
    1.讯飞输入法（iFly）
    2.小狼毫（weasel）
**Both the four can change the speed by shortcut keys under English.**
BTW, 微软&微信 have been updated high frequency， 讯飞 hasn't been updated since 2020.
![image](https://github.com/polywock/globalSpeed/assets/102582016/d7aca036-0bd9-4320-b2e1-b11d03f634b8)
