### ISSUE TITLE
请问如何导出谷歌系浏览器的全局快捷键设置

### ISSUE THREAD

**Issue by XMB-7** [polywock/globalSpeed#444]
不知有没有方法可以对浏览器的全局快捷键进行导出备份, 感谢.

**Comment by polywock** [comment]
Hello. In the bottom of the page, there's an export/import button.

**Comment by XMB-7** [comment]
感谢回复, 但好像这样进行导出是不包含全局快捷键的. 比如我给暂停播放这一功能设置了一个全局快捷键command a = alt+shift+1, 那么将之导出并在一台新电脑上导入后, 它只会恢复到, 暂停=command a=空, 而我仍需要手动将command a设为alt+shift+1.
所以我想问的是, 有没有办法实现所有全局快捷键的自动备份与恢复, 毕竟我的全局快捷键用得还是挺多的.

![image](https://github.com/polywock/globalSpeed/assets/65625632/d4479ee7-97b6-449c-ae28-c8f0f2a77bcb)

**Comment by polywock** [comment]
That's almost all the slots. I should probably add more 😆. 

Not possible I think. Browser-level shortcut keys must be set on a per-device basis. I think it's because of how dangerous they can be. If the user forgot they added a global hotkey, they might just tear out their hair in stress when their game/app doesn't work.
