### ISSUE TITLE
Does the gain control automatically capture audio?

### ISSUE THREAD

**Issue by A5Kush** [polywock/globalSpeed#482]
Hi,
First of all I'd like to say a special thank you for your work
your extension is a must have for my browser, I really appreciate it!

---

The issue:

I set up the extension to control: speed, pin tabs, and gain adjustments.
Speed control works very well

But the gain adjustments
If I don't click on the extension or use the shortcut to activate the extension
it doesn't work, and that's something every tab needs to do.

so, 
Please let me know if there are any settings 
that would save me the trouble of activating the extension every time
or is this a feature that could be enhanced? 
For example, audio capture can be automatically enabled every time the gain control is triggered.

Best Regards

**Comment by polywock** [comment]
Hello. Thank you! Glad you find Global Speed helpful. 

The Tab Capture API, which Global Speed uses to manipulate audio, requires the user invoke the extension for every tab. That's why it only works when you click the extension, or use a browser-level shortcut. Also won't work with a simple page shortcut. 

Most convenient workaround is to set up a Capture shortcut key in options page and use it to activate for each tab.
