### ISSUE TITLE
【BUG提交】在Chrome中调整音高无效

### ISSUE THREAD

**Issue by niubifengfeng** [polywock/globalSpeed#488]
过程：
在热键编辑器中，创建**音高**调整的热键。不论是+-还是=
不论是否勾选 “速度改变音高”。最终都不会改变视频的音高。

**Comment by polywock** [comment]
Hello. The pitch hotkey is unrelated to the "Speed change pitch" option. 

Speed change pitch: Means when you change the speed of a video, it will change the pitch as well. For example, 2x speed will sound high pitch. All videos have a preserve pitch setting, which will be turned off if this is enabled. 

Pitch shortcut: Uses algorithms to change the speed. Due to technical limitations, the pitch shortcut must be used with the 'tab capture' shortcut to activate it. 

![demos](https://github.com/polywock/globalSpeed/assets/31208859/c9b9aecb-71ce-4327-8f8d-e40f6f4db8c0)
