### ISSUE TITLE
BiliBili开启音量增益后视频无法全屏，全屏依然是网页全屏

### ISSUE THREAD

**Issue by SkyHeart90** [polywock/globalSpeed#491]
BiliBili网站视频，在开启音量增益后，全屏模式依然是网页全屏模式，关闭音量增益则恢复正常

**Comment by polywock** [comment]
Hi. Due to security concerns, the browsers limits fullscreen functionality while tab's audio is being manipulated. This applies to all websites, including Bilibili. 

To workaround this, you can create a Capture shortcut (捕获) in the options page. 

1. Turn off capture by using the shortcut. 
2. Enter fullscreen. 
3. Turn on capture by using the shortcut again.
