### ISSUE TITLE
Why can't I change playback speed from video player settings?

### ISSUE THREAD

**Issue by Agent-324** [polywock/globalSpeed#499]
The extension blocks me from changing playback speed from the video player settings and if the video player remembers the playback speed then playback speed constantly changes.

**Comment by polywock** [comment]
Hello.  It's hard/impossible to determine if the user intended to change the speed when they do it through the video player's settings. That's why Global Speed ignores any speed changes unless it's done through Global Speed's controls.

>  if the video player remembers the playback speed then playback speed constantly changes.

To solve this, you can try turning on Ghost Mode in the options page.

**Comment by Agent-324** [comment]
So it's not possible to change playback speed in video player settings while using the extension?

**Comment by polywock** [comment]
Exactly, unless you turn off the extension. The default hotkey to turn off the extension is Shift-Q on QWERTY keyboard, but you can also change it in the options page.

**Comment by Agent-324** [comment]
Ok thanks
