### ISSUE TITLE
And hey polywock and i would want you to make a seperate cent box too i would 

### ISSUE THREAD

**Issue by codeyr67** [polywock/globalSpeed#605]
hey polywock can you please at least make a seperate cent box too because i do not really want to make my own cent box or look for other apps that have that i do not because i want to able to pitch shift the song while watching the video on youtube i do just not audacity or adobe audition or nothing or ableton live either i do not i just want you to able to make a seperate cent box i do too i do and 96 semitones up and down still i do and i'll tell you how much i want in the seperate cent box i wanted 145.00 cents up and down i do you know one hundred and forty five cents i do so can you please make a seperate cent box with 145.00 cents up and down please like transpose pitch speed loop for videos extension has from google chrome

**Comment by polywock** [comment]
Hello. Please email me for further inquiries.

[global-speed-chromium.zip](https://github.com/user-attachments/files/17358842/global-speed-chromium.zip)

I won't be able to publish for a few weeks, so here's unpacked version if you want to use it now. 

1. Download the file and extract it. 
1. On Chrome, go to the extensions page -> chrome://extensions/?id=jpbjcnkcffbooppibceonlgknpkniiff
2. Enable "Developer mode" on the top right of the page. 
3. Click "Load unpacked" and load the extracted folder. 

There is no cent control but you can setup shortcuts to change the semitones by `0.01`. If you have questions about setting it up, you can ask `chatgpt.com` for assistance. Otherwise, please wait a few weeks.
