### ISSUE TITLE
Ability to Advance Audio as well as Delay

### ISSUE THREAD

**Issue by davidlovegrove** [polywock/globalSpeed#624]
First of all, love the extension.

I've sometimes come across videos where the sound is far behind the video (video happens first, then audio comes after). Would be great to have the ability to have advance audio. Appreciate this is slightly different as it requires the video to 'pause' while the sound keeps going, but would be a very handy feature to have.

**Comment by polywock** [comment]
Hello. Popular request, but hard to find a practical or generalized solution. 

The only function approach I've seen so far requires cloning a video, muting the original, and keep the clone hidden with the audio playing exactly where you want (delayed or advanced audio). The problem will be cloning the video. It would only work with simple videos that are linked to static video files on the internet. Like this for example.

https://storage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4

But, most video streaming sites have complex systems for loading/stitching video segments. Cloning will require investigating/reverse engineering each website individually to understand how they load the video. 

Even with this, it would be inefficient because it will double the bandwidth cost (loading two videos).

Someone figured out how to make it work for Youtube, where it only loads the audio, but it's no longer maintained and probably doesn't work right now. (https://github.com/adrian-ilie/av-sync).
