### ISSUE TITLE
Confusion about options page design

### ISSUE THREAD

**Issue by BlueDolphin9527** [polywock/globalSpeed#627]
Dear developer,

I find the design of your options page quite confusing and hard to understand. 

1. **blocklist and allowlist in URL rules**  
   In each URL rule, there is an option to set a blocklist or allowlist. How should this be understood? Normally, we set the entire software to be in blocklist or allowlist mode and then add the websites or items to allow or block. I really can't understand the design logic behind this in Global Speed.

2. **Default fixed `initial state` and its four options**  
   The default fixed `initial state` with the four options: *Previous tab's context*, *Global context*, *New context*, *Custom context* also confuses me.  
   The default fixed option should be used to make sure that each URL or tab (I'm not sure about this, could you clarify?) does not follow the overall speed and does not interfere with other URLs or tabs. But what exactly do the `initial state` and its four options do? 

Thank you for your attention to these points!

**Comment by polywock** [comment]
Hello! The UX definitely needs an upgrade. 

## Url Conditions 
For URL rules:  if the you add two websites (youtube.com and twitch.tv). 
- With blocklist mode, the URL rule will trigger on all websites except youtube.com and twitch.tv. 
- With allowlist mode, the URL rule will only trigger on youtube.com and twitch.tv. 


You can also add URL conditions to the shortcut keys, and in that case with  (youtube.com and twitch.tv). 
- With blocklist mode, the shortcuts will work on all websites except youtube.com and twitch.tv. 
- With allowlist mode, the shortcuts will only work on youtube.com and twitch.tv. 

## Pinning 

So by default, all tabs share the same context. If you change speed on one tab, it will also change speed on all tabs. But, if you pin a tab, that tab will become isolated and independent ([diagram](https://user-images.githubusercontent.com/31208859/149994031-64f491e2-6127-45da-ba49-00c1b23966ae.png)). 

I like the default behavior, but some people prefer all tabs to be separate. That's why I added the "pin by default" feature. Once enabled, all new tabs will automatically be pinned. 

The various options for `pin by default` give the user more control over the initial state. 

`Previous tab's context`: initial state will inherit the previous tab's state. For example, if you right click a video on Youtube and open it a new tab, that tab will inherit the same speed. This is useful if you like flexibility and continuity. 

`Global context`: initial state will inherit the global context. The global context is the context all unpinned tabs use. This isn't very useful, and I'm thinking of removing it. 

`New context`: initial state will empty. For example, speed will always be 1x for new tabs. This is useful if you want to always start at 1x speed. 

`Custom context`: if the user selects custom context, the current context will be saved, and all new tabs will inherit that saved context. For example: While the options page is open, the user can set the speed to 1.77x speed, and then changes the mode to `Custom context`. The current context (1.77x speed) will be stored and all new tabs will always start at 1.77x speed. This is useful if you want to always start at a specific speed.

**Comment by BlueDolphin9527** [comment]
@polywock  Thank you for your explanation. I now understand the URL rules and pinning behavior. However, I have a few suggestions:

1. Add a tip in the URL rules section: "Priority decreases from top to bottom. It is recommended to place blocklist rules at the top. New tabs will apply the rules accordingly."
  
2. Change **initial state** to **New tab settings**. Modify the word **context** to **settings** in the four options and add verbs to each.
   
   - **Previous tab's context** → **Use previous tab's settings**
   - **Global context** → **Inherit unpinned tab settings**
   - **New context** → **Set initialization**
   - **Custom context** → **Save current settings, new tabs will continue with these settings**
   
 Or, please consider adding this to the FAQ.

**Comment by polywock** [comment]
Hello. Thanks for the suggestions. Currently working on other projects, but I'll keep it mind for the next update. I've been neglecting the UX side of things.

**Comment by BlueDolphin9527** [comment]
Wish you all the best in your progress.

**Comment by Matthew-Harris-36** [comment]
I found a bug. When the first rule is a blocklist and the speed is set to 1, everything works fine. However, if the speed is turned off (global speed is disabled), the next two allowlist rules won't work.
![image](https://github.com/user-attachments/assets/e52c15b3-6557-4f0b-a67f-d666db1738c6)

**Comment by polywock** [comment]
Hello. So not really a bug, but a design choice.  You can duplicate the speed rules, and have it turn on the extension at the same time. Although, I'll probably change the behavior so it turns on by default as well. 

`bilibili allowlist` = speed `1.75`
`bilibili allowlist` = turn on 

`youtube allowlist` = speed `1.75`
`youtube allowlist` = turn on

**Comment by Matthew-Harris-36** [comment]
Thanks
