### ISSUE TITLE
Adding more visual adjustments to circle widget

### ISSUE THREAD

**Issue by Yassin-fan** [polywock/globalSpeed#637]
The current  circle widget when turned on only supports dragging (left/right or up/down) to fast forward/reverse and accelerate/decelerate, but do not support visual speed dragging settings (like the already existing functionality of clicking on icon). Therefore, if users want to quickly adjust the rate, they need to click on the icon in the top right corner before they can do it.

Would it be possible to add an option to turn on the ability, which can use  circle widget to accomplish visual quick acceleration/deceleration (e.g. mouse over the  circle widget to show the speed drag setting bar)

Thanks for making the plugin, it works great!

**Comment by polywock** [comment]
>Thanks for making the plugin, it works great!

Thanks, that means a lot. 

As for the feature suggestion, I'll probably not work on it. The circle widget was designed for mobile so has to remain very simple. It was also very complex to implement because there is so many edge cases on mobile. I'm generally afraid to make changes because each change requires thorough testing on Firefox and Edge android devices. Testing on mobile is pretty cumbersome at the moment.  So I hope that I never have to touch that thing again. It gives me anxiety just thinking about it. 😆
