### ISSUE TITLE
Low audio quality on speed <1

### ISSUE THREAD

**Issue by Funkelfetisch** [polywock/globalSpeed#65]
awesome work :)!
love it for soundcloud on firefox.

one question though: Rekordbox and all the DJ tools can slow music down without the interference or "audio-artifacts" that appear with this plugin.

And idea on how they do that, and how to improve playback quality when lowering the speed?

**Comment by polywock** [comment]
Different browsers use different time stretch algorithms. Some users say Firefox uses a lower quality time stretching algorithm compared to Chromium, so that might be the issue.  If you're talking about pitch preservation... 

1. Go to option page. 
2. Go to "Options" panel. 
3. Click on 3 dots to show more options. 
4. In the Speed Preset section, enable the 0.5 to 1.5 slider. 

That would add a slider speed control where you can also conveniently enable/disable pitch preservation.
