### ISSUE TITLE
[Feature Request] Always pin for a domain

### ISSUE THREAD

**Issue by Nova38** [polywock/globalSpeed#7]
## Feature Request

- [ ] Allow in the configurations page for the ability to automatically pin tabs for a given domain.
- [ ] Set default settings for the pinned domain

The main reason I think this would be a great thing to add is movie\tv websites like Netflix and Hulu that don't always buffer ahead if you have it set to a fast speed. This would let those websites be launched by default in a pinned mode, with a default speed, so that it wouldn't require the extra step every time.

@polywock  Thanks for the work you have done on this project! It is fantastic.

**Comment by polywock** [comment]
Thanks. Wow, more than 3 months passed since I saw this. Yikes, sorry for the long delay. The update took longer than expected (and I had less free time than expected). The refactor took a while. It feels like a small project, but it's surprisingly large.  The URL rules have been implemented and published. It should take a few days to a week to publish.
