### ISSUE TITLE
Video Delay

### ISSUE THREAD

**Issue by speaker-60** [polywock/globalSpeed#70]
Could we have a video delay option

Using bluetooth headphones and i know the exact ms i need to delay the video so that audio from my bluetooth earphones sync up. 

Or if you can let us push the audio sync into negative numbers aka allow the audio to play before the video

**Comment by polywock** [comment]
There's an [extension](https://chrome.google.com/webstore/detail/youtube-audiovideo-sync/mknmhikmjljhpccebpnplhicmcfjkgbk) for Youtube that may be of help. It mutes the Youtube video, and loads a separate audio only stream with the time position shifted. This is the only approach I found that works so far, but it's hard or even impossible to extend to other sites.

**Comment by speaker-60** [comment]
yer i know of the extension but for netflix and other sites :(

What about pushing audio forward so the reverse of delay even if it cuts of the start of the audio it would allow to offset the audio to match the delay

I basically need to set the audio delay to -0.347 currently i cant set negative numbers in vcl player this is how i match the delay setting the audio delay to -0.347

**Comment by polywock** [comment]
I'm not sure that's feasible. Maybe try opening the video on two tabs. One muted, the other not. And shift the position of one so it syncs up to your need. This will make it hard to pause and it will cost double the data bandwidth, but may be worth it on some sites (Netflix won't work because you can't load the video twice).
