### ISSUE TITLE
Speed display issue with some websites

### ISSUE THREAD

**Issue by ShrirajHegde** [polywock/globalSpeed#74]
Set on website:
![image](https://user-images.githubusercontent.com/66936172/113917225-927bb400-97fe-11eb-9820-706ae77d1901.png)

set using Global speed:

![image](https://user-images.githubusercontent.com/66936172/113917108-6f510480-97fe-11eb-9dee-cd47c2933757.png)

any way to solve this issue? (global speed sets to 1.5000000000000004 instead of 1.5, similar for other speeds too)

This screenshot is from [odysee.com](odysee.com) but happens to many sites which use similar video speed controls.

**Comment by polywock** [comment]
Thanks, I was able to reproduce the bug. We would expect `1.1 + 0.1` to equal `1.2`, but because floating point math isn't precise, it calculates to `1.2000000000000002` or whatnot. Usually, it's not a problem because the website rounds the result before displaying the speed.  To fix, I'll round the result to the nearest third decimal digit.
