### ISSUE TITLE
Lag after Resume

### ISSUE THREAD

**Issue by orkhan10** [polywock/globalSpeed#80]
Thank you very much for this beautiful extension guys. It really is a game changer!

I just wanted to bring one thing into your attention. Right now the speed setting I have for a site is applied after a few hundred milliseconds. 
I am reading something in a foreign language while listening to its audio. Sometimes I want to pause to catch up to the speaker but each time I resume, the playback starts at 1x and only adjusts the speed after a short delay.

Is this a limitation or can it adjusted? (Or maybe at least make the delay shorter?)

**Comment by polywock** [comment]
Glad the extension could be useful. As for a solution, try enabling ghost mode in the options page. Ghost mode blocks the website from changing the speed (or in this case, resetting the speed back to 1x).

**Comment by orkhan10** [comment]
Thank you very much! It worked! 
Is there a donation page? I could not see it here or on chrome extensions page. I would love to buy you a coffee.

**Comment by polywock** [comment]
Just finishing setting up a [Github Sponsors](https://github.com/sponsors/polywock) profile. Thanks! ❤️

**Comment by orkhan10** [comment]
> Just finishing setting up a [Github Sponsors](https://github.com/sponsors/polywock) profile. Thanks!

Great! But I think "Buy me a coffee" is more seamless as you don't have to create an account or add credit card infos to save it there like in Github. Just an opinion. Cheers!

**Comment by polywock** [comment]
I definitely agree. I did try setting up a Buy Me a Coffee account with Stripe but got scared away because the "Public info" section showed my name, address, phone number, etc. They also seem to expose donators email, credit card last 4 digits, failed transactions, and it didn't seem too anonymous to me. Paypal with Buy Me a Coffee doesn't seem any better as well. 

The thing I like about Github Sponsors is that it doesn't seem to expose private information from either party except the the Github profile. 

Thanks for the coffees!
