### ISSUE TITLE
About Bilibili Live Interface

### ISSUE THREAD

**Issue by 123456qewret** [polywock/globalSpeed#86]
Hello developer, first of all, thank you for the development of this plugin, it's very practical, but i would like to give a feedback on a small problem.
In the bilibili live interface, volume control, timeline control doesn't work, and sound is intermittent,  just like the following link, hope it will be fixed, thank you very much!
https://live.bilibili.com/6

**Comment by polywock** [comment]
Thank you, glad Global Speed could be useful. As for the issue, volume control seems to work fine for me, but for timeline control, Bilibili Live player checks the video's currentTime multiple times a second, and if it detects the video isn't where it should be, it reverts the position back. I've experimented with a few workarounds, but none seem ideal enough to implement. But, if you want to use it, here's the code. 

```
javascript:(() => {
    if (!window.ogDesc) {
        window.ogDesc = Object.getOwnPropertyDescriptor(HTMLMediaElement.prototype, "currentTime");
        window.ourDiv = document.createElement("div");
        window.ourDiv.setAttribute("style", `position: fixed; left: 0px; top: 0px; width: 100vw; height: 100vh; z-index: 999999999;`);

        Object.defineProperty(HTMLMediaElement.prototype, "currentTime", {
            set: function(v) {
                if (window.frozenMap) {
                    window.frozenMap.set(this, v);
                } else {
                    ogDesc.set.call(this, v);
                }
            }
        });
    }

    const showColor = (color, duration = 100) => {
        window.ourDiv.style.backgroundColor = color; 
        document.documentElement.appendChild(window.ourDiv);
        window.showTimeout && clearTimeout(window.showTimeout);
        window.showTimeout = setTimeout(() => {
            window.ourDiv.remove(); 
        }, 200);
    }

    if (window.frozenMap) {
        window.frozenMap.clear();
        delete window.frozenMap;
        showColor("#ff0");
    } else {
        window.frozenMap = new Map();
        showColor("#7ad");
    }
})();


```

This javascript when run blocks Bilibili from changing the time position. 

## Setup
1. Open Global Speed options page. 
2. Create a Javascript hotkey and input the above code. I set mine to the "F" key. 
3. Add a URL condition so that the hotkey only runs on "live.bilibili.com". 

## Usage 
1. It only works if the video frame is focused, so make sure to click on the video or pause button before using the hotkey. 
2. Trigger the javascript hotkey. Mine is set to "F" key. Once it activates, it should show a blue screen. 
3. Now you should be able to use the rewind/forward keys without it being reset. Once you're finished, you could trigger the javascript hotkey again to disable it. Once disabled, it should show a yellow screen. 

Demo: 

https://1drv.ms/v/s!AtBBLfHu3pI1coc8xNuARyBj0pw?e=eGRTvW

**Comment by 123456qewret** [comment]
Oh, It's my fault that I didn't describe the live problem clearly. The volume cannot be controlled only after the picture quality is switched. This situation doesn't occur on Twitch or Huya, just Bilibili live. Also thanks for the JS it's really useful!

**Comment by polywock** [comment]
No problem, glad I could be helpful. I was able to reproduce the issue. Looks like Global Speed is prioritizing the wrong video. Once you change quality or pause for a long time, Bilibili hides the original video element and creates a new replacement. If there are multiple videos on the page, Global Speed tends to prioritize the longest video. But, since they're all live, the duration is all Infinity.  If the volume controls don't work, you will need select the real video. 

![demo](https://user-images.githubusercontent.com/31208859/118376814-4b6ca580-b598-11eb-86e1-4440f7799c3b.png)

**Comment by 123456qewret** [comment]
So that's how it is,  I used to use shortcut keys to control every function in Globel Speed, I didn't notice about it because i hided the extention's menu. Thank you very much for your help, hope it will be solved in the next version.
