### ISSUE TITLE
建议添加一个让视屏窗口全屏的快捷键

### ISSUE THREAD

**Issue by Arost01** [polywock/globalSpeed#87]
建议添加一个让视屏窗口全屏的快捷键

**Comment by polywock** [comment]
Implemented in the latest update (version 2.8.2). There's two modes. 

Basic/Native mode: 
Smart

**Comment by polywock** [comment]
Thanks for the suggestion. Implemented in the latest update (version 2.8.2). Published on Chrome/Firefox, but will take a week to get approved for the Edge store. The fullscreen hotkey has two modes. 

Basic / native mode: Global Speed enters fullscreen directly on the video element and simple native controls are shown. This version is cleaner and may be preferred for some people, but if you rely on subtitles, it's not very useful. 

Smart mode: this mode is more complicated and tries to mimic the website's original fullscreen design. In most cases, the website doesn't enter fullscreen directly on the video element, but instead a container element which contains all the subtitles, controls, video, etc. For this mode to work, you must first enter fullscreen without the new hotkey so that Global Speed can learn how to find the container element. 

It may not be compatible with some sites. Let me know if you experience issues.
