### ISSUE TITLE
can not  uses keys to cotrol the video while i use full screen mode  in Media Gallery

### ISSUE THREAD

**Issue by yovelga** [polywock/globalSpeed#95]
can not  uses keys to cotrol the video while i use full screen mode  on Media Gallery

**Comment by polywock** [comment]
I'm not sure what Media Gallery is, could you link me the site?  

A few things could be the problem. Do all speed control hotkeys not work as well? 

1. The website isn't using an HTML video. 
2. Global Speed isn't prioritizing the correct video element. To ensure it is, you can select the correct video. 

![testt](https://user-images.githubusercontent.com/31208859/121588365-d5772500-ca03-11eb-85dd-40a9fc119ec5.png)

**Comment by polywock** [comment]
I'm not sure what Media Gallery is, could you link me the site, or provide screenshots or screen recordings? Since the controls seem to work without fullscreen, it's possible it's still working in fullscreen mode, but the visual feedback is hidden. Depending on what container element is in fullscreen, the visual feedback won't show up.

**Comment by yovelga** [comment]
![image](https://user-images.githubusercontent.com/85686263/121848829-4152d980-ccf3-11eb-98d4-c362e40171f9.png)

**Comment by yovelga** [comment]
![image](https://user-images.githubusercontent.com/85686263/121848941-69423d00-ccf3-11eb-9c29-84f4071a03c3.png)

**Comment by yovelga** [comment]
you'r Solution  only works when I use two screens and open another website on the second screen

**Comment by polywock** [comment]
That looks to be Kaltura. That platform is a chronic headache (#73) .

It was troublesome to diagnose. The problem was that Kaltura videos are inside of a blank iFrame, which don't seem to register event listeners before the iFrame is fully loaded.  

I've implemented a fix on the latest update (2.8.8). It's already be approved on the Firefox and Chrome Web Store, but will take a week for the Edge Addon store.
