### ISSUE TITLE
It would be perfect if can synchronize the configuration

### ISSUE THREAD

**Issue by Wirili** [polywock/globalSpeed#96]
It would be perfect if can synchronize the configuration

**Comment by polywock** [comment]
Since some users (like me) don't like sync, I've tried implementing it before as an optional feature. But, it got complicated real quick and I had to roll back.  Hopefully the export/import and copy/paste feature is a good enough compromise for now. I'll also try adding a "sync upload" and "sync download" feature to make export/import more convenient.
